### ISSUE TITLE
Image required for blog posts?

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/hotosm-website#100]
Trying to update broken link to GitHub on https://hotosm.org/node/495/edit (extra space at the end) and I can't save because an image is required.

**Comment by xamanu** [comment]
@mikelmaron Yes, the new design made them practically required. In the transition this can be annoying, yes. But please pick a nice photo for the post. Or in case you don't want to, just upload this again: https://hotosm.org/sites/default/files/styles/normal/public/500px-Hot_logo_0.png?itok=0YIc74gz

Closing here...
