### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#102]
Hi, where did Jobs end up on the new website? I remember we had talked about a link in the footer (but that would only make sense if we had other navigation links in the footer)

**Comment by xamanu** [comment]
Yes, jobs went away. We have it in the system but not linked anywhere. We could put them under "Get Involved".

**Comment by xamanu** [comment]
Jobs are back on the "Get Involved" page: https://hotosm.org/get-involved
Please check wording. Thanks!

**Comment by TylerRadford** [comment]
great
