### ISSUE TITLE
Require Post Summary

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#103]
Related to posts/comments in issue #99 - I think people are often posting on rather short notice/timeframe and we should assume they won't use the summary unless it is required/expanded upon default. Several of the recent posts have had 'duplicate images' shown on the front page (this happens if images are embedded in the post and no summary given). I believe the best avoidance is just go ahead and require summary text (with no images allowed).

**Comment by xamanu** [comment]
This is definitively something to write in the manual #101. No need to make a post summary requiered.
