### ISSUE TITLE
Small layout fixes on homepage

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#104]
- Suggest moving top Nav menu outside of marquee image (currently menu items get obscured by image)
- Suggest making menu text larger and/or more visible (perhaps white text on red background upon rollover) -- currently some of the main text on the body of the page is bigger than the menu item text

![image](https://cloud.githubusercontent.com/assets/9853903/15130448/6e870b54-1616-11e6-8081-fec1a249eec8.png)

**Comment by xamanu** [comment]
I think here the main problem is the selected background image here, which has text in it. This is not very suitable when displaying the menu on top of it. I wouldn't like to change the design in such a strong way as suggested here.

Maybe we should include a note about image selection in the manual (#101).

**Comment by TylerRadford** [comment]
Hi @KatjaUlbert @mellig what other design suggestions might you have for us here? @xamanu is right that the text in the image doesn't help, howeer I still believe the top navigation menu needs to be more prominent (size, color, or otherwise), even if there is no text in the background image.
