### ISSUE TITLE
Multiple featured projects

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#105]
Enhancement request: ability to have multiple featured projects on the homepage (with only one displayed at a time)

One could be randomly selected upon page load
OR
Scroll through (slowly) the multiple projects, leaving each one displayed for 5-10 seconds

**Comment by xamanu** [comment]
:heavy_check_mark: Done

Out of the pool of features projects on each page load one gets loaded randomly.
To make a project a "featured project", select "Promoted to front page" on project nodes.

**Comment by TylerRadford** [comment]
Cool. Thanks @xamanu
