### ISSUE TITLE
Enhancement request: user photo above name in News items

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#111]
Request to add the user's photo above their name in the News item single node page, in order to give it a more personal feel. For example in the screenshot below, Douglas' photo would appear above or below his name.

![image](https://cloud.githubusercontent.com/assets/9853903/16494037/ccfea30a-3eb5-11e6-9561-84c59621a101.png)

**Comment by smit1678** [comment]
A version of this was implemented on the new website.
