### ISSUE TITLE
Typo on About page: Collaborative Maps for Humanitarian Aid section

### ISSUE THREAD

**Issue by gregrs-uk** [hotosm/hotosm-website#114]
Presumably this:

> To **data** over 3,500 Missing Maps volunteers have collectively made 12 million edits to OpenStreetMap and put 7.5 million people on the map.

should read:

> To **date** over 3,500 Missing Maps volunteers have collectively made 12 million edits to OpenStreetMap and put 7.5 million people on the map.

**Comment by bgirardot** [comment]
Thank you very much for letting us know! Fixed! Cheers @gregrs-uk
