### ISSUE TITLE
Add annual report section to website

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#117]
We have completed our 2015 annual report in pdf format. Can we add a place for it on the website?

The bottom of the "About" page could be a good place to add a new block. Perhaps we could merge the one usefile file from the "Incorporation" block in with the "Bylaws" block in order to free up space for an Annual Report block.

![image](https://cloud.githubusercontent.com/assets/9853903/18592288/461d4602-7c04-11e6-9abf-f62ca0e8b96d.png)

**Comment by xamanu** [comment]
Of course! No problem to do that. And we can have this by the start of HOT Summit.

**Comment by xamanu** [comment]
@TylerRadford you can edit the page of the annual report here if you wish: https://hotosm.org/annual_report

**Comment by xamanu** [comment]
The annual report block is on the website.
Feel free to edit https://hotosm.org/by_laws to include https://hotosm.org/incorporation
