### ISSUE TITLE
User Profile, Working Group role

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/hotosm-website#12]
For Working Groups, the role will be different per group. Might make sense to be a drop down too. How much trouble is it to amend that? If it's a bit of work, perhaps we just start off without the role.

**Comment by xamanu** [comment]
This works for the selection on users now. They can be assigned to working groups. There is a (still not completely public) overview: http://hotosm.org/working-groups

* We need good texts for them: #49
* It is missing to show related users on the bottom of each working group.

**Comment by xamanu** [comment]
All questions are in sub issues and this is live -  so closing.
