### ISSUE TITLE
Improve Site Image Quality

### ISSUE THREAD

**Issue by DylanMoriarty** [hotosm/hotosm-website#120]
On a Retina screens most of the images for the site are noticeably grainy around the edges:

<img width="780" alt="screenshot 2017-02-08 10 39 12" src="https://cloud.githubusercontent.com/assets/9341928/22744258/e03eebe8-edea-11e6-9fc5-ba227c4faf8f.png">

<img width="245" alt="screenshot 2017-02-08 10 43 06" src="https://cloud.githubusercontent.com/assets/9341928/22744450/65e03b08-edeb-11e6-9c52-5d51b02ef612.png">

This can be easily fixed either making the images slightly larger and scaling down via the css, or just saving em' as svgs.

Happy to update update them if anyone wants to throw me access to PR to this repo.

**Comment by bgirardot** [comment]
@xamanu @KatjaUlbert Any objection to  @DylanMoriarty going ahead to work on this? You both should have introduction emails from Dylan in the membership email.

**Comment by pantierra** [comment]
No, not at all. Welcome @DylanMoriarty I just gave you access to this repo. Any questions, please don't hesitate to ask.

I think almost all svg's are in [this folder](https://github.com/hotosm/hotosm-website/tree/master/sites/default/themes/hot_theme/images/source-files).

Cheers!

**Comment by DylanMoriarty** [comment]
Awesome! Thanks man. Having the original SVG's handy is a godsend.

The fix itself should be quick, but I can't say I've run a Drupal based development environment before! Took a quick peek at it the last weekend but got bogged down pretty quick.  Lots of install.txts. @xamanu are there any quick start guides you could recommend to getting it running locally?

**Comment by smit1678** [comment]
Issue related to old version. Closing.
