### ISSUE TITLE
Upload Annual Report

### ISSUE THREAD

**Issue by vannicer** [hotosm/hotosm-website#122]
Any advice on how to upload the Annual Report as it exceeds doc upload size

**Comment by grinapo** [comment]
(Alternatively you may investigate whether it could be shrunk in the meantime. Possibly extreme high res imagery is not strictly required.)

**Comment by smit1678** [comment]
This was implemented by using a link to a Google doc: https://www.hotosm.org/annual_report. New website will not have a size restriction.
