### ISSUE TITLE
Assemble spreadsheet to outline content blocks

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#127]
Based on our discussion on Monday, we need to assemble a spreadsheet of specific content that will need to be generated as the work begins. We want to work with real content and not lorem ipsum. The spreadsheet will be used as a way to organize and start writing content before a site is up.

**Comment by smit1678** [comment]
Here is the initial spreadsheet for content blocks: https://docs.google.com/spreadsheets/d/1CecktuqEGuCUcNxK8FBWfCXbfzCppNNaH9qsBR7ag7o/edit?usp=sharing

**Comment by bgirardot** [comment]
Does the new website maintain the blog aspect of the current website and grouping blog posts by major project area?

And the membership functionality where each voting member gets a page that shows how they contribute, e.g., working groups and projects they contribute to?

**Comment by bgirardot** [comment]
I guess it does based on other issues in this repo. sorry, just saw the spreadsheet and didn't see any mention of those items.

**Comment by russdeffner** [comment]
I added some comments directly on the spreadsheet, take or leave them, looks like a good start.

**Comment by russdeffner** [comment]
The community WG flushed out 'roles' a year or two back, results (and links to more info) on the wiki: https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team#Community_Types_and_Roles 
This is regarding the Get Involved List of roles/persona types so we wouldn't have to start from scratch.

**Comment by smit1678** [comment]
> The community WG flushed out 'roles' a year or two back, results (and links to more info) on the wiki: https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team#Community_Types_and_Roles
This is regarding the Get Involved List of roles/persona types so we wouldn't have to start from scratch.

@russdeffner Thanks for linking that. I don't think that was brought up previously but might have been brought up indirectly when we were looking at this last summer in https://github.com/hotosm/design-strategy/issues/15. That resulted in a bigger list as well as some user interviews which were documented here: https://docs.google.com/spreadsheets/d/18E7eaX-KF-D_IoBxm34V3Y6J3uAetK71JYSHr0gBl5Y/edit?usp=sharing

> Does the new website maintain the blog aspect of the current website and grouping blog posts by major project area?

@bgirardot Good question. It'll still include the linking between blog posts with projects and project area. We haven't sorted out whether the blog aspect will be integrated directly into the site or leverage a blog platform like Medium. Need start a separate thread about that with some pros and cons and make a decision. 

> And the membership functionality where each voting member gets a page that shows how they contribute, e.g., working groups and projects they contribute to?

From what @xamanu mentioned in #124: 

> We also had a connection of user profiles and working groups, as well as user profiles with board, staff or membership list... But I guess those were not very successful. Manually maintained lists seem to be easier to handle in the HOT website workflow.

He brings up the point we've previously discussed, that they will still be a part of the site but just the question of how they are maintained -- manual has been the most successful in the past since most people don't keep their profile up to date.

**Comment by TylerRadford** [comment]
@RebeccaFirthy in DC we agreed to take the lead on drafting hotosm.org website text with Rachel. Since Rachel is traveling I got us started. Can you pls review what I already wrote? This is a draft - you can completely cut and propose new language if you don't like what is already there. We also need content for community support programs, "partner with us" pages

**Comment by smit1678** [comment]
Closing this out since we've implemented the initial content on the site for launch. We'll open up new individual tickets to track content updates and new content.
