### ISSUE TITLE
Review and outline type of data integrated into project pages

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#128]
Project pages will look to integrate data from external tools and services to provide a more updated and live picture of what is happening in the project. To start, we need to determine what would we like and what is possible.

**Comment by smit1678** [comment]
@brendangatens Here is an initial summary of project page data that we should be able to get from each source.  

This is really just a summary of the main type of data that we could potentially get from each source and doesn't really go into ways we could show each one yet. 

Potential Data: 

- TM 
	- Task number, name, description
	- Task completion and validation status
	- area that is being mapped

- OSM Analytics API or Missing Maps API
  - should be able to get number of buildings, km of road collected by Tasking Manager projects or Country

- MapCampaigner
  - Campaign title
  - area that is being mapped
  - Number of features collected
  - Type of features collected 
  - Percent of area covered by mapping

- HDX or Export Tool - Public Exports, or datasets that are added to HDX
  - File name, description
  - HDX endpoint and download link 

- OpenAerialMap
  - Thumbnail preview
  - name and details of image
  - footprint and bounding box of image

**Comment by smit1678** [comment]
Two weeks ago @TylerRadford @dakotabenjamin and I chatted about ideas for project and country pages as a way to evolve the conversation from what we listed above. 

We began the discussion by outlining some of the questions we thought should be answered by the pages: 

* What is happening / what are we doing? 
* How do I get the data? 
* How can I contribute? 

We talked through the above list of potential data sources and landed on the following as a good, feasible start for both Project Pages and Country pages: 

1. User Entered location of the project
    * this is either an exact location or polygon. This may be a manual process to generate this but could be more automatic based on TM projects extent or MapCampaigner extent. 
2. Tasking Manager data
    * Task number, details, and AOI
    * Task completion and status
    * Overall stats - num of users and activity
3. OSMA API
    * num of buildings
    * km of road by TM or country
4. File download or links
    * HDX or Export Tool download links
    * OAM download links
    * Visualize Change link

Other ideas we discussed: 

* Have links to Start Mapping if there are active Tasking Manager projects
* Make sure that if we're showing that this is an active project on the project page, that information also shows up on a project listing. 
* We can start by manually entering TM projects but for sustainability, it would be good to have this linked to the campaign tracking that is being integrated into the TM. We want to make this is as automated as possible. 
* In Kampala we also discussed linking to other country based access portals or maps. Uganda country page links to an operational data portal that the country is using. 

Shot of whiteboard sketching: 

![img_2098](https://user-images.githubusercontent.com/796838/37032421-6175ac6e-213a-11e8-91e6-31ab601082a9.JPG)

### Next actions

@dakotabenjamin @DylanMoriarty @brendangatens @xamanu and anyone else, let's meet at the end of the week if we can to discuss how we manage and do maps across the site. Related to #141.

**Comment by ramyaragupathy** [comment]
## Country page data requirements:
@smit1678 - Using this ticket to outline the data requirements for country pages. This is just the first version, I'll keep updating this ticket with details and prototype screenshots as we brainstorm.

TM can fetch all mapping projects and their centroids for now. We need to look at a way to bundle community projects as well. In addition to the centroids from TM it'd be nice to have,
- the project country
- total edits for each project
- total number of mappers for each project
- total area covered

These properties could be used for styling the map and ordering/sorting the cards within the country page. Individual project IDs return most of these details, but it would be nice to have it all aggregated in one place for us to fetch.

**Map:**
- Show the centroid of all projects within the country by a dot
- This dot radius could be adjusted based on number of edits/ number of mappers involved.
- Hovering over the circle should give additional details on the project in a pop with a link to TM page
- Yearwise filter within the map. Only those years across which project were activated are displayed.
- Removed the logo from the bottom-left, instead placed the year filter. Not sure if this would lead any copyright issues. Attribution info icon is still present in the bottom-right

**Project cards:**
- In addition to type of program and country, added the impact area to the card as well. 

**Stats:**
- Total number of projects in addition to existing stats



![image](https://user-images.githubusercontent.com/12103383/40349290-d01296c6-5dc3-11e8-907a-9e0e4421644f.png)




![image](https://user-images.githubusercontent.com/12103383/40349105-2c361c26-5dc3-11e8-9cd2-6b92edd733f7.png)

**Comment by ramyaragupathy** [comment]
## Project pages

![image](https://user-images.githubusercontent.com/12103383/40490459-31f8acb0-5f89-11e8-8c0e-48ff3b78c074.png)


**Stats**

- Mappers involved 
- Area covered by the project
- Edit count 
- Feature Count 

**Map**

  - Current project area highlighted
  - Option to get back to country level view of all projects
  - Tile active in the last 24 hrs
  - Tile opacity can be adjusted based on edit counts
  - Progress over a period of time showing how tiles status changed from `yet to map -> mapped -> validated `

**Other details**
- Project description
- Organisers
- Impact Area
- Duration

TM returns:
- project area
- individual task boundary and status of each of the task
- features mapped

What more is needed for each project?
- Number of tasks yet to be mapped, mapped, validated for the whole duration of the project. Granularity should be on daily basis for the progress bar to show the project growth
- Feature count for each feature (Need to check the availability with the API once it is up). 

Not all the data requirements for project need to be fetched used TM. We could borrow some of the data capabilities of OSM Analytics as well.

**Comment by ramyaragupathy** [comment]
## Landing page

**Stats**

  - Total number of projects
  - Total num of countries
  - Total area covered
  - Total edits
 -  mappers online
  - tasks Mapped


**Map**
- Projects active in the last 24 hrs shown as a pulse
- A heat map of all projects. Current heatmap in the gif below.
- We could have two tabs: country view & heat map view 

![pulse](https://user-images.githubusercontent.com/12103383/40584606-78e884bc-61c1-11e8-847a-f9fbd457d5a7.gif)
![heatmap](https://user-images.githubusercontent.com/12103383/40584765-74d14a28-61c4-11e8-913f-d2929df0bbc1.gif)

**Comment by ramyaragupathy** [comment]
## Summing up Data Requirements
@smit1678  - Striking out those directly available as part of TM API

**Landing page**
  - ~Mappers Online~
  - ~Tasks Mapped~
  - ~Total Mappers~

**Country level**
- ~Centroid of projects~
- Project count for each country
- Yearwise project list
- Feature level edit count, would like to know the most mapped feature
- Mapper count (with expertise level, we could use it for analysis may be?)
- Total area covered
- Project active in the last 24 hours based on task status

**Project level**
-  ~Area covered~
- Total mappers
- ~Total number of tasks~
- ~% mapped, % validated~
-  Feature level edit count for projects at block/task level
- Feature level edit count for overall project
- ~Task status change over the duration of the project~ (available for each task)
- Last active timestamp based on task status change



<details>
<summary><h3>TM API</h3></summary>

**[All Projects](https://tasks.hotosm.org/api/v1/project/search)**

- Returns an object with three properties:
    - mapResults
    - results
    - pagination
- `mapResults.features` holds all the project details in an array
    ```
    {
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [18.4438176099286, -1.94603531516757]
			},
			"properties": {
				"projectId": 4591,
				"priority": "URGENT"
			}
		}
    ```
- `results` is an array of 14 projects that appears in the first page
- `pagination` holds details that helps fetching data from multiple pages

**[Individual Project](https://tasks.hotosm.org/api/v1/project/3597?as_file=false)**
- `lastUpdated` - Does this depend on just change of state of task blocks? If so we could use this for finding the project active in last 24 hours

```
{
	"projectId": 3597,
	"projectStatus": "PUBLISHED",
	"projectPriority": "HIGH",
	"areaOfInterest": {
		"type": "MultiPolygon",
		"coordinates": []
	},
	"tasks": {
		"type": "FeatureCollection",
		"features": [{
			"type": "Feature",
			"geometry": {
				"type": "MultiPolygon",
				"coordinates": [
					[
						[
							[-99.1557311834105, 19.3901817463959],
							[-99.1543578923951, 19.3901817463959],
							[-99.1543578923951, 19.3914771385913],
							[-99.1557311834105, 19.3914771385913],
							[-99.1557311834105, 19.3901817463959]
						]
					]
				]
			},
			"properties": {
				"taskId": 1341,
				"taskX": 58869,
				"taskY": 145469,
				"taskZoom": 18,
				"taskSplittable": true,
				"taskStatus": "VALIDATED"
			}
		]
	},
	"defaultLocale": "en",
	"projectInfo": {
		"locale": "en",
		"name": "Mexican Earthquake | 2017 Sep 19 - Mexico City - first suburbs affected",
		"shortDescription": "A powerful earthquake (magnitude 7.1) jolted central Mexico on Tuesday, cracking building facades and scattering rubble on streets in the capital on the anniversary of a devastating 1985 quake. Its epicenter was near the Puebla state town of Raboso, about 76 miles southeast of Mexico City.\n\nBut major destructions affected the central city of Mexico. This is the first list of affected zones in this city.",
		"description": "A powerful earthquake (magnitude 7.1) jolted central Mexico on Tuesday 19 September 2017, cracking building facades and scattering rubble on streets in the capital on the anniversary of a devastating 1985 quake.\n\nIts epicenter was near the Puebla state town of Raboso, about 76 miles southeast of Mexico City.\n\nEvent Name: **Puebla Earthquake**\n\nType of Event: Sudden Onset\n\nGeographic Scope: Region (Puebla State, and Mexico City State, in central Mexico)\n\nEstimated Humanitarian Impact: significant casualties are likely (36% chance 100-1000, 34% chance 1000-10000)\n\nEstimated Duration: Medium\n\nNote: part of this HOT project was covered by the older (but still active) [project #1202](https://tasks.hotosm.org/project/1202) in the central Mexico City but with additional goals (including streets and open areas), created in for the National Earthquake Simulation Drill in 2015.",
		"instructions": "Imagery: please use **Esri World Imagery**\r\n\r\nDon't hesitate to subdivide cells if there are too many buildings.\r\n\r\n`Basic roads are mapped, we are mapping buildings`\r\n\r\n**How to contribute:**\r\n\r\n1. Pick a square.\r\n\r\n2. If there is nothing map, add a comment and mark the task as done.\r\n\r\n3. If you see buildings and roads that haven't been traced, please trace them.\r\n\r\n4. Upload your edits by clicking save and mark the task as done.\r\n\r\n5. If you're not done, unlock the task and someone else can complete it.\r\n\r\nUse the \"Split\" link if a task square is too big to finish in 10 mins or so. \r\n\r\nThese are somewhat big task squares because most of the area is lightly populated, but they all have to be checked.\r\n\r\n\r\n\r\n\r\n**Tags to use:**\r\n\r\n**Buildings**\r\n\r\n* building=yes\r\n\r\n**Roads**\r\n\r\n* highway=unclassified (only if you add some of them). Use \"residential\" if you are confident it is, but it could  be also \"pedestrian\" or \"service\" (for public transport). In doubt, use \"unclassified\".\r\n\r\n\r\n**Feature Examples:**\r\n\r\n\r\n**Buildings**\r\n\r\n![alt text](https://github.com/mataharimhairi/images/blob/master/fiji-building-polygon.png?raw=true \"Building\")\r\n\r\n\r\n**Roads**\r\n\r\n![alt text](https://github.com/mataharimhairi/images/blob/master/fiji-road-polyline.png?raw=true \"Road\")\r\n",
		"perTaskInstructions": ""
	},
	"mapperLevel": "INTERMEDIATE",
	"enforceMapperLevel": true,
	"enforceValidatorRole": false,
	"private": false,
	"entitiesToMap": "Buildings only- Solamente edificios",
	"changesetComment": "#hotosm-project-3597 #PueblaEarthquake #MexicoCity #OSMMX",
	"dueDate": null,
	"imagery": "",
	"mappingTypes": ["BUILDINGS"],
	"campaignTag": "Disaster Response",
	"organisationTag": "OSM-MX",
	"licenseId": null,
	"allowedUsernames": [],
	"priorityAreas": null,
	"lastUpdated": "2018-05-16T19:41:09.584301",
	"author": "Verdy_p",
	"activeMappers": 0
}
```

**[Task Activity](https://tasks.hotosm.org/api/v1/project/3597/task/1)**

```
{
  "taskId": 1,
  "projectId": 3597,
  "taskStatus": "VALIDATED",
  "taskHistory": [
    {
      "action": "STATE_CHANGE",
      "actionText": "MAPPED",
      "actionDate": "2017-09-21T13:46:45.036093",
      "actionBy": "Mich74"
    },
    {
      "action": "STATE_CHANGE",
      "actionText": "VALIDATED",
      "actionDate": "2017-10-04T11:14:51.539245",
      "actionBy": "ranjithjoy"
    },
    {
      "action": "LOCKED_FOR_MAPPING",
      "actionText": "",
      "actionDate": "2017-09-20T19:57:17.896953",
      "actionBy": "RichRico"
    },
    {
      "action": "LOCKED_FOR_MAPPING",
      "actionText": "",
      "actionDate": "2017-09-21T07:16:25.458094",
      "actionBy": "ranjithjoy"
    },
    {
      "action": "LOCKED_FOR_MAPPING",
      "actionText": "",
      "actionDate": "2017-09-21T13:30:50.227530",
      "actionBy": "Mich74"
    },
    {
      "action": "LOCKED_FOR_MAPPING",
      "actionText": "",
      "actionDate": "2017-09-21T11:53:37.653037",
      "actionBy": "Nerdanel"
    },
    {
      "action": "LOCKED_FOR_MAPPING",
      "actionText": "",
      "actionDate": "2017-10-04T11:12:44.004627",
      "actionBy": "ranjithjoy"
    },
    {
      "action": "COMMENT",
      "actionText": "ran out of time, still some buildings left to map",
      "actionDate": "2017-09-21T12:48:35.640393",
      "actionBy": "Nerdanel"
    },
    {
      "action": "LOCKED_FOR_VALIDATION",
      "actionText": "00:00:32.753562",
      "actionDate": "2018-04-06T07:25:46.794206",
      "actionBy": "lluisvicens"
    }
  ],
  "perTaskInstructions": "",
  "isUndoable": false
}

```





</details>

**Comment by mataharimhairi** [comment]
**Landing Page // Feedback**
* Stats: total edits - might be more useful to viewer to see total buildings, roads and waterways mapped. This information could be pulled from OSM Analytics.
* Map: heat map view - not sure if the heatmap is needed, keeping it as simple as possible with all the necessary information is best. Otherwise can be confusing for users regarding the difference.

**Country Page // Feedback**
* Stats: total edits - same as above
* Status: project - provide viewers quick insight into what stage the project is at. This would be very helpful for those wanting to get involved and participate, either remotely or through collaborating (cross-initiative) on the ground.
* Map: dot radius - really like the idea of the size being based on number of edits, to show where/what project most of the work is currently focused
* Map: filter - really like the idea of being able to filter projects based on year, would be good to have an 'Active' filter as well to show projects that viewers can participate in
* Link: OSM data - link to Export Tool/HDX country datasets (https://export.hotosm.org/) 
                              - buildings (https://data.humdata.org/dataset/hotosm_npl_buildings)
                              - roads (https://data.humdata.org/dataset/hotosm_npl_roads)
                              - waterways (https://data.humdata.org/dataset/hotosm_npl_waterways)
                              - pois (https://data.humdata.org/dataset/hotosm_npl_points_of_interest)
* Link: option to get back to landing page
* Contact: like the information about the voting members. Perhaps a link to that voting member would be good, if the viewer would like to get in touch?

**Project Page // Feedback**
* Map: tile active in last 24 hrs - this is great. will show which projects are getting a lot of focus, which general correlates to the importance. 
* Map: tile opacity - tiles/tasks could be colour coded based on legend used in TM to show the status of tasks
* Link: visualisation - link to Visualize Change tool with visualisation for that project showing the mapping changes over time (http://dev.visualize-change.hotosm.org)

@ramyaragupathy These are all the points we covered in the call, but let me know if there is anything that is still unclear.

**Comment by ramyaragupathy** [comment]
Similar to #187 - suggest we close here @smit1678
