### ISSUE TITLE
Finalize initial styles

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#131]
To continue on building out from the wireframes from #125, initial visual styles from @brendangatens laid out on to the wireframes are here: https://marvelapp.com/7bdc9h0/screen/36822336

*comment updated by @smit1678*

**Comment by smit1678** [comment]
We added a short page documenting font, colors, and logo currently in use: https://github.com/hotosm/hotosm-website/wiki/Colors,-Fonts,-and-Logo.

For future reference, there is a http://www-dev.hotosm.org/playground endpoint that shows styles that can be reused. Opened up a new ticket to track the style guide development. https://github.com/hotosm/hotosm-website/issues/232
