### ISSUE TITLE
Evaluate search options

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#133]
Marking as a todo. We'll want some type of simple text search to enable quickly finding older projects or posts. Need to evaluate how we'll implement.

**Comment by smit1678** [comment]
To update here with a couple ways to approach from some initial research: 

1. write some custom javascript or leverage something like https://www.npmjs.com/package/simple-jekyll-search. [Example custom search is from Development Seed](https://developmentseed.org/)
2. use something like [lunr.js](https://arcath.net/2016/02/setting-up-lunr-js-in-jekyll/)

Both seem to involve creating a json file that can be searched. We'd need to look to make sure titles, subtitles, keywords that are searchable. By focusing on this and communicating, we can also make sure that titles and subtitles describe the post and content well. 

Other ideas? 

I think a full text search solution is overkill and not quite necessary. I also don't think we want to go the Google custom search engine route.

**Comment by dakotabenjamin** [comment]
![image](https://user-images.githubusercontent.com/1847818/38368081-57ba5654-38b2-11e8-98bc-5d1ef32fb5bb.png)

Now it needs to be styled...

**Comment by brendangatens** [comment]
@dakotabenjamin is this on a branch somewhere? Happy to get started styling when ready.

**Comment by dakotabenjamin** [comment]
![image](https://user-images.githubusercontent.com/1847818/38448016-3f6a624c-39cf-11e8-96eb-785ad192dbdf.png)

Some issues remain and it is a little beyond my front-end skills

- [ ] The overlay isn't scrolling (it was working once but I'm not sure how to get it to work again)
- [ ] Animations would be nice
- [ ] Need an "X" instead of the arrow placeholder
- [ ] Could use feedback on what information to display in the results

**Comment by Dragneel7** [comment]
@dakotabenjamin I could try working on frontend part modifying your existing work.

**Comment by smit1678** [comment]
@Dragneel7 I think @brendangatens was/is going to knock out the styling for this. Do you want to pick up on https://github.com/hotosm/hotosm-website/issues/154 for the time being?

**Comment by Dragneel7** [comment]
@smit1678 I can work on that.

**Comment by dakotabenjamin** [comment]
See #177 for the Search addition PR
