### ISSUE TITLE
Add more info about Jekyll to readme

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#135]
To be helpful for newcomers to using Jekyll to set up and run the site locally, may be helpful to add some more information about install Jekyll in the readme.

**Comment by donovanglover** [comment]
Hello,

I'd like to work on this, but I think it's best to have a separate `CONTRIBUTING.md` file for contributors. This way the information can be as detailed as it needs to be without affecting the size of the readme. [Example](https://github.com/github/explore/blob/master/CONTRIBUTING.md).

**Comment by smit1678** [comment]
@GloverDonovan Yes, totally agreed about having a contributing document. We've been trying to add those in all our other repositories. I think this specific ticket was about installing Jekyll and making sure the README had enough information for anyone to get the site up and running locally.

**Comment by donovanglover** [comment]
I should have a pull request that fixes this issue soon.
