### ISSUE TITLE
Develop Our Work map and interaction

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#141]
From #131, need to develop the map and interactions for the Our Work section. Location for the header in Our Work page: http://www-dev.hotosm.org/our-work.

![hot our work 2018-03-05 14-46-52](https://user-images.githubusercontent.com/796838/36981091-21365e84-2084-11e8-8506-f124895211e6.png)

Prototype of interaction here: https://framer.cloud/mTeKY

@brendangatens Guidance on what we're seeing on the map?

**Comment by dakotabenjamin** [comment]
Is the map here going to be slippy or just an image?

**Comment by smit1678** [comment]
Recap of our discussion on Friday: 

Three immediate spots for maps: 
1. Our Work page that shows coverage of HOT projects and community members. Serves as a navigation point for country pages. 
2. Country pages. Will have a static map for now centered over the country: http://www-dev.hotosm.org/where-we-work/uganda. These will evolve into more robust views of data outlined in #128. 
3. Profile pages. These are static maps of the location where the member is. Example: http://www-dev.hotosm.org/people/nate-smith.html

We outlined a few initial actions last week: 

* @brendangatens will create a Mapbox style in the HOT mapbox account
* @DylanMoriarty is going to investigate interaction and polygon styles for the Our Work map. 

@dakotabenjamin were you jumping onto something at the moment? do you want to start building out the country page?

am I missing anything? @brendangatens @DylanMoriarty can you drop a quick update on the progress here?

**Comment by DylanMoriarty** [comment]
I haven't cranked on this completely yet, but think I've got a good battle plan for it.

### New Frontmatter
The code for a map will be included in the global site javascript, but only run if 'map' is defined in the frontmatter. That value will either be interactive (project page) or static (country/profile).

I'm pretty sure the only other variable we really need is the Country name somewhere. It would be fantastic if those matched by the country abbreviations, but we can match it by country name too (might be easier for the people inputting & lead to less errs).

Natural Earth Data (Open Source geo data) has a [pretty robust bounding box JSON](https://gist.github.com/graydon/11198540) we can use for this. For hover states, Natural Earth Data also has great country outlines -_that will not line up perfectly to OSM_- but should well enough that someone would only notice it if they zoomed allllll the way into a countries border.

More neatly said:

| Name        | Values           | Effect  |
| ------------- |:-------------:| -----:|
| map    | interactive / static | This will be used by the script to determine what type of map to build out  |
| countryAbbr      | US, AF, AO... etc      |  This will be used to determine which country to be started on. |

### Next Steps

My steps for this week will be to get the map drawn on the page. Then I'll need to chat with Brendan on how we want to handle toggling between the interactive/static-ness of the project page map.

@brendangatens can you share the map id & public token for it with me on Slack? Should look something like:

```
'pk.eyJ1IjoibWFwdGltZWRjIiwiYSI6ImNqMGJjYTBmdzA...';

&

mapbox://styles/maptimedc/cj0to2bhs00842rqrb370qzgd
```

**Comment by willemarcel** [comment]
Notes from the meeting with @smit1678 and @dakotabenjamin 

Profile pages:
- get the member location from lat/lng field or from country name

Our Work page:
- Polygons filled with a colour if we have project/members on it
- Interactions also with a list of Continents > Countries (only those with projects/members will be shown)

**Comment by willemarcel** [comment]
When creating the style in Mapbox Studio, we need to add the country data from Natural Earth. Tutorial: https://www.mapbox.com/help/style-single-country/

That way we can colour the countries areas dynamically with Mapbox GL JS. Please share on Slack also the dataset id and the style layer name.

**Comment by smit1678** [comment]
Initial work is online and completed. Added a task related to filtering the map view based on impact area, https://github.com/hotosm/hotosm-website/issues/231. 

Closing this out in preference for new tickets based on specific updates.
