### ISSUE TITLE
Tools and Data page

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#143]
For first version, add these initial sections to align with user needs: 
  - Plan mapping
  - Editing the map
  - Get OSM Data
  - Analyze OSM Data

After this initial layout, we'll review gaps and see what other information we should be adding to this page, i.e. Github and other resources.

**Comment by smit1678** [comment]
@brendangatens We have all the pieces in place now, correct? 

If so, next action is to review and update the draft content.

**Comment by smit1678** [comment]
Initial content is online but additional tools need to be added and linked: http://www-dev.hotosm.org/tools-and-data

**Comment by russdeffner** [comment]
Added HOT ID Curriculum in Siteleaf; otherwise looks good.

**Comment by russdeffner** [comment]
Actually guess I have one questionable: Field Papers?

**Comment by smit1678** [comment]
> Actually guess I have one questionable: Field Papers?

yeah let's add

**Comment by smit1678** [comment]
FYI, I updated the language at the top of the page to better fit the purpose of that section: Tools we use instead of Our tools. We might want to update that section to be Tools we maintain and only list the tools that are actively developed, and then list all the tools we use in the subsequent sections.  

<img width="555" alt="humanitarian openstreetmap team tools data 2018-05-28 15-14-45" src="https://user-images.githubusercontent.com/796838/40618590-de0f869c-6289-11e8-96f8-9be99e330b23.png">
