### ISSUE TITLE
Community and Organization page

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#144]
For first version, following is to do on the Community and Organization Page: 
  - hold on adding a local initiatives section, discuss about if we want to have this or just keep as linking to projects
  - Working Groups - describe what they are, links to a list of Working Groups page with module with description and links to get involved in that working group 
  - Add module for HOT Summit
  - Add module for Support - link to default page, figure out what content is on there
  - Finances and Annual Report - module that links to PDFs and archived PDFs

**Comment by russdeffner** [comment]
Re: Working Groups - it would be great if we could get the calendar embedded in the website: https://calendar.google.com/calendar/embed?src=hotosm.org_848e89aaiab04ag94d23rqn558@group.calendar.google.com

**Comment by smit1678** [comment]
This page has been reviewed and update with content, links, etc: http://www-dev.hotosm.org/community/. Calendar integration broken out into separate ticket. 

Closing this out in preference for new tickets on specific updates.
