### ISSUE TITLE
Get Involved page

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#146]
For initial version of the Get Involved page, to do: 
  - Keep user and country selector to see how it can work
  - Replace events module with Jobs, link to Jobs landing page 
  - Add other modules based on wireframe layout and content

**Comment by smit1678** [comment]
@brendangatens We have all the pieces in place now, correct?

If so, next action is to review and update the draft content.

**Comment by brendangatens** [comment]
@smit1678 my country selector doesn't seem to be working, but yes, ready for review and content considerations.

**Comment by smit1678** [comment]
Initial review done, content added, and country selector working. Closing this out in preference for other tickets about specific updates.
