### ISSUE TITLE
Jobs landing page and individual pages

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#147]
For initial jobs page at `/jobs`
  - Jobs landing page is just a list of active jobs. will need to filter based on date or add a hidden flag for landing page but keep job page live. 
  - Create individual jobs pages `/jobs/new-job/`

**Comment by brendangatens** [comment]
Example job up here: http://www-dev.hotosm.org/jobs/communications-and-social-media-intern.html
