### ISSUE TITLE
Add support for multiple authors in Updates

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/hotosm-website#148]
It should be set up like this in the _posts file:
```
Person:
- Hawa Adinani
- Amelia Hunt
```
which currently looks like this:
![image](https://user-images.githubusercontent.com/1847818/37034879-be962468-2118-11e8-8340-deb5de4a0d09.png)

I think putting a line break in there will make the names render correctly, but I'm not sure how to do it  in the layout.

**Comment by dakotabenjamin** [comment]
@brendangatens If you haven't already worked this out I'll take a shot

**Comment by brendangatens** [comment]
@dakotabenjamin I haven't done this yet. Might just need to loop through people as we already do for countries and working groups just below. I can look at this later today if you don't get around to it.

**Comment by dakotabenjamin** [comment]
Here's what I've got:
![image](https://user-images.githubusercontent.com/1847818/39009307-4163ef82-43d9-11e8-9908-6176703d3226.png)
