### ISSUE TITLE
Restructure "Get involved" and "Who we are" sections

### ISSUE THREAD

**Issue by wonderchook** [hotosm/hotosm-website#15]
I think we need to be strategic about the top level headers on the website. I think it makes more sense for the working groups to go under "Get Involved". 

I'm thinking that instead of having a "Leadership" tab that should be switched to "Who we are" or something like that. That way we would have under that tab but Leadership and Voting Members. 

Thoughts?

@mikelmaron

**Comment by jeffhaack** [comment]
Could somebody explain to me the current functionality for adding a job posting?  I can't figure out how to post a job on the site.  The only thing under "Get Involved" now is the "Missing Maps Roster", which it says is a static page.  I am guessing this is different than adding an "Update", which is the only thing I can do.  Any help?

**Comment by mikelmaron** [comment]
@jeffhaack, currently you create a "Static Page", then add it to the "Get Involved" Book, in the Settings panel in the bottom. 

Also, I updated permissions so you (and other Content Editors) can create new Static Pages.

**Comment by jeffhaack** [comment]
cheers Mikel

**Comment by xamanu** [comment]
Note to myself: Remove book navigation on the bottom of nodes.

**Comment by xamanu** [comment]
A first preview of this restructuring can be reviewed at the staging site: http://hotosm.mapanica.net (user and password is "hotosm").

Missing:

- Text for call to action for Activations (Wanna map?) 
- Text for working group
- Show users by their working group (#48)
- Job functionality (#28)

**Comment by xamanu** [comment]
ok. This is coming to an end. Please review on the staging site: http://www.dev.hotosm.org (user and password is "hotosm").

There is a new structure with all the new views for members, board, jobs and working groups. And we use a second level menu (#29).

Please give feedback, so we can proceed and push this live. Thank you!

**Comment by xamanu** [comment]
It's finally live! :)
