### ISSUE TITLE
Frontpage stats

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#154]
One the frontpage we're planning to have stats integrated. We need to sort out what stats and where we are getting them. 

A simple near-term solution would be to leverage the Missing Maps stats API, https://osm-stats-production-api.azurewebsites.net/stats/missingmaps, plus the Tasking Manager, https://tasks.hotosm.org/api/v1/stats/home-page. 

![humanitarian openstreetmap team home 2018-03-14 14-44-14](https://user-images.githubusercontent.com/796838/37409404-2e1c3f9c-2796-11e8-9878-9e8138799fc8.png)

**Comment by Dragneel7** [comment]
@smit1678 Can you please explain what exactly do we have to add more in the pre-existing stats.
Thanks

**Comment by smit1678** [comment]
@Dragneel7 Certainly. For this task, we want to dynamically add the numbers from each API endpoint onto the page. There are two different API endpoints we'll need to hit in order to generate these stats. You can see an example of how this is implemented on http://www.missingmaps.org/ towards the bottom of the page [(source code)](https://github.com/MissingMaps/missingmaps.github.io). 

For the four data points: 

* Community mappers should come from the Tasking Manager API endpoint: https://tasks.hotosm.org/api/v1/stats/home-page
    - Community mappers: `totalMappers`
* The remaining should come from the Missing Maps API endpoint:  https://osm-stats-production-api.azurewebsites.net/stats/missingmaps
    - Total map edits: `edits`
    - Buildings mapped: `buildings`
    - Roads mapped: `roads`

**Comment by Dragneel7** [comment]
I get it. @smit1678 thanks for explaining, I'll get started to implement this feature.

**Comment by smit1678** [comment]
Implemented https://github.com/hotosm/hotosm-website/blob/gh-pages/js/main.js#L1-L12
