### ISSUE TITLE
Hook up country selector on Get involved page

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#162]
Input works with country dropdown but doesn't link to page yet

**Comment by Dragneel7** [comment]
@smit1678 I would like to  work on this issue. 
Can you tell me where the form action should be redirected to?

**Comment by smit1678** [comment]
thanks @Dragneel7, sounds good. Here's what the action should be: 

- User selects the dropdown and sees the list of countries (how it works right now)
- Then when the user selects a country, it should take them to the country page, i.e. http://www-dev.hotosm.org/where-we-work/bangladesh/

I don't think we need to do anything more than that.

**Comment by dakotabenjamin** [comment]
This is fixed in `random-fixes`
