### ISSUE TITLE
Change HOT involvement metadata field to list for projects

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#167]
Change from free text to two items: 
- HOT Program
- Community-lead

**Comment by brendangatens** [comment]
I've created an `Is Community-Led` checkbox on each project. If this isn't checked as true, the project will default to being a _HOT Program_. What do we think? An alternative way of doing this could be to create a drop-down with the two options. In order for this to work though, we would have to create a _HOT Involvement_ collection containing just the two options; might be overkill unless we start adding more involvement types.

<img width="633" alt="screenshot 2018-04-02 10 26 47" src="https://user-images.githubusercontent.com/1270986/38191581-3da9ad8a-3661-11e8-8843-e4651eb04b19.png">

**Comment by dakotabenjamin** [comment]
Can we close this?
