### ISSUE TITLE
Broken images links

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/hotosm-website#178]
Here's how to fix broken images in projects: 
1. Find the page on the active/old website with the working image
  - http://hotosm.org/microgrants_and_community_development leads to https://www.hotosm.org/projects/microgrants_and_community_development
2. Find the image name by opening the image or copying the link: `https://www.hotosm.org/sites/default/files/styles/banner/public/**2017%20microgrants_0_3_0.png**?itok=q4lpPJFE`
3. Add this line to the project's markdown file: 
```
Feature Image: https://s3.amazonaws.com/hotwww/files/old/styles/banner/public/<image-name>
```

**Comment by smit1678** [comment]
This is mostly complete. Let's open up new tickets as remaining issues arise.
