### ISSUE TITLE
Separate frontpage stats from main.js

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#185]
The frontpage stats load on every page via main.js: https://github.com/hotosm/hotosm-website/blob/gh-pages/js/main.js#L1-L12. We should consider separating them so they only load when needed -- on the main page.

**Comment by dakotabenjamin** [comment]
Changes here: https://github.com/hotosm/hotosm-website/commit/071145d6000bd7c1164327ad02c7968597670fd4
