### ISSUE TITLE
Project page layouts

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#187]
From #128, here a couple potential project layouts from @brendangatens on how additional maps could be integrated into project pages: 

![project 1](https://user-images.githubusercontent.com/796838/39115558-b3313cfa-46ea-11e8-8140-2f90d1b25835.png)

![project 2](https://user-images.githubusercontent.com/796838/39115629-f44510d6-46ea-11e8-8ad6-54275d29afde.png)

![project 3](https://user-images.githubusercontent.com/796838/39115652-fdeaf5e2-46ea-11e8-9049-69c2e07d654d.png)

> trying to create a template that’s somewhat open knowing that there will be various types and sources for this data. The top white box could be an open field in the CMS that we can add text and images to. If there’s overflow in that white box, we can set it to scroll. The grey box would contain any view controls that we need (Before/After, View Day 1 vs Day 3, maybe a date picker for longer projects or a slider to show progress). And like the other maps on the site, I’d see more controls (zoom, maybe an interactive key) appearing once the user chooses to _Explore the map_.

> there are some types of data that might be better suited in the body of the project, rather than up in the header map. Like if we were to display the _Number of Changesets and Contributors_ graph, it might be better for the story of the project if it sat within the body of the project, where there might be more context around it.

**Comment by ramyaragupathy** [comment]
Capturing page layout ideas in #128:

- [Landing page](https://github.com/hotosm/hotosm-website/issues/128#issuecomment-392342072)
- [Country page](https://github.com/hotosm/hotosm-website/issues/128#issuecomment-390902379)
- [Project page](https://github.com/hotosm/hotosm-website/issues/128#issuecomment-391742794)

**Comment by ramyaragupathy** [comment]
More notes from a discussion with project-managers:
https://paper.dropbox.com/doc/Project-Pages--APeOPbcw92_CsiSjf~fELti~Ag-akFMtCxVl7EPUN4lDQj4r

**Comment by ramyaragupathy** [comment]
@smit1678 -Can we close this for now as we roll out our new changes? We could revisit/sketch out a different ticket for future design improvements.
