### ISSUE TITLE
Add code of conduct page

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#189]
Content here: https://www.hotosm.org/hot_code_of_conduct

Anything we want to add/change on this page?

**Comment by russdeffner** [comment]
Maybe some of the spacing, but noting that the text would have to be altered by Board. But what were you thinking would possibly need/want changed?

**Comment by smit1678** [comment]
Correct, not proposing to change wording. Only layout, how we link, and whether we put the full text on a page or just link to a google doc.

**Comment by dakotabenjamin** [comment]
Using one of the layouts that already exists: 
![image](https://user-images.githubusercontent.com/1847818/39277725-43d88a64-48bd-11e8-9944-bc15b2a02109.png)

**Comment by dakotabenjamin** [comment]
Updates are here: https://github.com/hotosm/hotosm-website/commit/12ab7219f8bb43c2c4be1796b298cb636c3f25d4

**Comment by smit1678** [comment]
Added at http://www-dev.hotosm.org/code-of-conduct
