### ISSUE TITLE
Hook up subscribe link

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#192]
Entering email results in `405 Not Allowed`

![image](https://user-images.githubusercontent.com/796838/39188747-3a599a26-47d9-11e8-9f52-b397feda1d58.png)

**Comment by dakotabenjamin** [comment]
Aside- is the offset for that header text supposed to look that way?

**Comment by smit1678** [comment]
> Aside- is the offset for that header text supposed to look that way?

Yeah I think thats right

**Comment by dakotabenjamin** [comment]
This is here: https://github.com/hotosm/hotosm-website/commit/1f0e595fb1190ca3d6310b8c10cb2c72cf521a4a

**Comment by smit1678** [comment]
Works!
