### ISSUE TITLE
HOT Team - Should be HOT Staff

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#204]
This seems minor, but HOT has always been about working as a team of volunteers.

It would be good if we kept that spirit and identified staff as staff, who are also part of the team of course, but using Team to describe  the staff is less inclusive of the volunteers.

**Comment by smit1678** [comment]
:+1: agreed by several other people and this was adjusted: http://www-dev.hotosm.org/staff/. Finalizing layout on the page and populating with new and missing staff.
