### ISSUE TITLE
Present projects depending on their type and highlight ongoing projects (emergency mapping)

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#21]
I don't know what you think: But for visitors who want to get involved in one of the activations and arrive to the website it is almost impossible to understand which projects are really active. 

How has this been handled until now? There is a checkbox on the projects that promotes it to the front page. Are all projects ongoing activations?

I would propose to highlight the really active projects, that need people to jump on, on the project page in a slightly different background or seperate them from the others with a suitable headline like "Get involved in this projects now" and "Long term projects" and maybe "Archived projects",.... something like that.

And on the frontpage we could make a more calling headline to the block of projects, like the first one in the projects overview page for the ongoing activations.

**Comment by xamanu** [comment]
Ongoing, future or past could be done by the use of a drop-down, which has to be changed when the state changes. Or a date field to specify start and end date (the second one is optional). I'd go for this solution, because this way we collect the information about the exact dates of the projects, at the moment of happening. This information is not held anywhere (the wiki is a little bit inconsistent).

**Comment by techlady** [comment]
A good way to handle it would be to have big "buttons" on the Home page that lead to the current activations. Obviously, the top one would be the most urgent activation. The buttons should be big enough that they would be readily visible to someone looking to join an effort, such as Nepal. Probably they should be on the right side. It should be easy to create, remove or change the order of buttons. 
I don't like drop-downs because they would not be visible when someone lands on the page. And we can't use the word "activations" because no one knows what it means but people already in HOT.

**Comment by techlady** [comment]
As for Felix's four categories of projects, they look good to me.

**Comment by xamanu** [comment]
Thanks for the input @techlady!!! I also agree that these activations should be very visible. There is a new graphic design in planning (#23) and I'd suggest to focus bigger visualization changes all together with this.

Let's focus here first on getting the technical base for categorizing the project implemented and visualize the ongoing activations as such. This is a relatively small improvement but should go into the right direction.

**Comment by techlady** [comment]
Yes, but don't use the word "activations"

**Comment by xamanu** [comment]
@techlady :+1: makes absolutely sense.

**Comment by techlady** [comment]
I still like Felix's types of projects:
Community Development
Emergency Mapping
Technical Development
Am I missing one? I seem to remember that he had a fourth category and that it made sense to me.

**Comment by techlady** [comment]
Xamanu.

Let's finish with the basic outline before we start getting into how to do it graphically. Once we know what page headings we want, then we can come up with graphics.

**Comment by xamanu** [comment]
"Field deployment" was the forth category :)

**Comment by techlady** [comment]
How is the different from "Community Development"?

**Comment by russdeffner** [comment]
I would say that "Field Deployment" highlights more of the projects where HOT 'compensates' people for field work. Community Dev more like missing maps where HOT isn't directly financing anyone to go, but generally supporting the effort.

**Comment by wonderchook** [comment]
I would say "Field Deployment" isn't ideal calling is the "Field" is well...not great people live in that "Field". Also is it still a Field Deployment when people that live there are compensated to work on community development?

**Comment by russdeffner** [comment]
Agree Kate - and I think it is fine to join deployments in community dev.

**Comment by xamanu** [comment]
The communications working group proposed in today's meeting the following categories for projects:

* Disaster Mapping
* Community Development
* Technical Projects

And to use a date field for the information about past, ongoing or future projects,

**Comment by xamanu** [comment]
So, we know have two new fields on project nodes: "Project type" and "Timespan". I'd like to ask somebody go through all projects and fill in this information, so we can work on the visualization. Thank you!

**Comment by techlady** [comment]
Delix,

         It's Time Span, two words.

Charlotte


At 06:42 AM 5/19/2015, you wrote:

>So, we know have two new fields on project 
>nodes: "Project type" and "Time Span". I'd like 
>to ask somebody go through all projects and fill 
>in this information, so we can work on the visualization. Thank you!
>
>
>Reply to this email directly or 
><https://github.com/hotosm/hotosm-website/issues/21#issuecomment-103499183>view 
>it on GitHub.

Charlotte Wolter
927 18th Street Suite A
Santa Monica, California
90403
+1-310-597-4040
techlady@techlady.com
Skype: thetechlady

**Comment by techlady** [comment]
Filling in all the information could take some time. Besides, I think only Tyler knows all the projects. I say we give this to him, at least to get started. Then we ask each project coordinator to add some details, maybe giving them a suggested length, such as 100-125 words (about a quarter page).

**Comment by techlady** [comment]
By the way, how are we going to display the information about each project. A headline and a picture followed by a paragraph of text? Then a link to the project page (which will grow as each coordinator adds text and pictures)?

**Comment by xamanu** [comment]
@techlady, i fixed "time span". Thanks! Yes, Tyler offered to go through the projects. I'm going to send him an email.

**Comment by xamanu** [comment]
On the staging site I have a basic proposal separating the projects by type and by time (ongoing/archived): http://www.dev.hotosm.org/projects (user/password is "hotosm")

**Comment by russdeffner** [comment]
Looking good - I would suggest we 'chop' the text - maybe just the first paragraph or even just a 'learn more' link.  I think once we have all the tech projects also on the page, we'll be a bit crunched for space; so maybe also smaller image/icons?

**Comment by xamanu** [comment]
Makes sense. I just cut off the whole description text and made the titles bigger. I like it a lot more now.

**Comment by xamanu** [comment]
This is now live. :+1:

**Comment by xamanu** [comment]
There is also now a short entrance to ongoing activations on the end of the emergency mapping introduction page: http://hotosm.org/emergency-mapping
