### ISSUE TITLE
Our work - map and "see where we work" button

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#210]
Countries with no projects can be clicked on takes you to a blank page
no legend
See where we work button just adds a legend. Exit map does not exit the map, just removes the legend.
No indication of countries where we have projects and members.
see where we work region and country links navigation means a lot of clicking the back button because there is no persistence.

**Comment by smit1678** [comment]
thanks @bgirardot, couple responses. This map isn't fully complete but it's also a bit of an experiment so some feedback is good. 

The map is meant to be interacted with. Right now legend is after you interact so it might be helpful to expose that before the interaction. Countries that have no projects are meant to be clicked as we want to promote country views of areas that don't have projects or members. The purpose is to encourage thinking about starting projects within that country. The country pages, with or without projects, will have some additional statistics about OSM data and community members. 

> see where we work region and country links navigation means a lot of clicking the back button because there is no persistence.

Region and country links are meant to be an alternative to using the map as navigation as it might not be clear which specific countries or if you're not familiar with using a map to navigate. 

What might be an interesting way to further develop is to have a link like http://www-dev.hotosm.org/our-work#south-america that takes you directly to a region view.

**Comment by ramyaragupathy** [comment]
Implemented through https://github.com/hotosm/hotosm-website/pull/346
