### ISSUE TITLE
What we do page - formatting issue

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#211]
See below. The text is hard to read on the image. Not sure if there is supposed to be text on the image or it is all related to the formatting issue.

looks the same in chrome and firefox

![2018-05-01_11h06_01](https://user-images.githubusercontent.com/265831/39481057-642c96ac-4d27-11e8-8b4c-08abe7718363.png)

**Comment by smit1678** [comment]
Related to #207
