### ISSUE TITLE
Add info icon/text for stats bar

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#221]
It would be helpful to have a icon with hover or text with a link that helps explain the stats bar. Frontpage stats are only showing Missing Maps hashtag, while country page stats show all edits within that country. This is a limitation of the OSM Stats API at the moment. 

![fireshot capture 10 - humanitarian openstreetmap team_ - http___localhost_4000_where-we-work_uganda_](https://user-images.githubusercontent.com/796838/39749665-39431842-52ab-11e8-9e50-18cff02c3182.png)

**Comment by ramyaragupathy** [comment]
Addressed through https://github.com/hotosm/hotosm-website/pull/237
