### ISSUE TITLE
Look to add loading icon or fill with placeholder number for country and landing page stats

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#222]
Depending on performance of APIs, the landing page and country page stats bar does not fully populate until loaded. We could look to prefill or use a loading icon to help show that the data is loading. 

Side note: could also be solved by pre-generating data to be loaded with the website.

**Comment by ramyaragupathy** [comment]
Fixed through https://github.com/hotosm/hotosm-website/pull/220
