### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#23]
The website right now is not very responsive and looks not very good on mobile devices and smaller tablets. It would be good to offer a responsive design for smaller resolutions.

This might be good to implement with a general design overhaul. But it should be in the list here to not forget and implement at least within the next half a year or so...

Opinions? Ideas?

**Comment by xamanu** [comment]
A real redesign is going to be planned. Some stuff happened end of last year. Here is the document, so we do not loose anything at least: 

* https://hackpad.com/HOT-Website-redesign-WCUe4mmltqk
* http://prk.ng/hot/HOT-webdesign-v1.jpg

This is a bigger task and needs a special initiative.

**Comment by xamanu** [comment]
@KatjaUlbert I would like to have a mobile-first design approach. What do you think?

**Comment by KatjaUlbert** [comment]
Yes! Any technical guidelines as to size etc?

**Comment by xamanu** [comment]
Nothing defined, yet. So you are free to propose. Or ask more specifically.

**Comment by xamanu** [comment]
Implemented and online. Thank you everybody who was part of this!
