### ISSUE TITLE
Task banner and Tasking Manager implementation

### ISSUE THREAD

**Issue by brendangatens** [hotosm/hotosm-website#230]
A while back we discussed implementing a banner showing an urgent task from the Tasking Manager. Here’s a quick mockup of what this could be.

![task-banner](https://user-images.githubusercontent.com/1270986/39992464-ca242bb2-576a-11e8-8dd4-0ce74c99391c.png)

Some initial ideas were to manually add this whenever a new task was deemed urgent, or to automatically display the most recently posted task.

Feel free to use this to discuss the larger plan of integrating active tasks into associated projects and countries. The overall goal—as I understand it—is to make hotosm.org more of an operational hub rather than just a portfolio and point of contact.

**Comment by TylerRadford** [comment]
This is great. I'd vote for turning this on/off manually.
And perhaps making it a bit shorter/take up less space on page.
Urgent mapping is the most common use case, but we have other types of uses for this as well - end of year funding appeal for example.

**Comment by TylerRadford** [comment]
Possible use cases
1. Urgent mapping task
2. Donation campaign
(with 1. and 2. sometimes happening concurrently)
3. Major calendar event like a HOT annual Summit/conference

**Comment by willemarcel** [comment]
Solved.
