### ISSUE TITLE
Add missing projects and connect to impact areas

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#236]
Review our [impact areas sheet](https://docs.google.com/spreadsheets/d/1CecktuqEGuCUcNxK8FBWfCXbfzCppNNaH9qsBR7ag7o/edit#gid=1313512021) and add missing projects.

**Comment by TylerRadford** [comment]
There are three remaining and have asked owners to add them

**Comment by TylerRadford** [comment]
METEOR
GED4ALL
Uganda Open Cities mapping
