### ISSUE TITLE
Email subscription for news

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#24]
Taken from https://github.com/hotosm/hotosm/issues/10

Implement a simple newsletter functionality to send news (content type "update") out to people who left their email address in some subscription block on the website.

**Comment by xamanu** [comment]
Yes, there is a simple mailchimp module we can use for. Now that @wonderchook is not with us (in HOT) anymore, I'm asking @mikelmaron and @jaakkoh, who might know who is managing this now.

**Comment by wonderchook** [comment]
@KristenEgermeier manages this.

**Comment by KristenEgermeier** [comment]
Hi @xamanu ,
Sorry for the delayed response, catching up after the Summit.  I manage mailchimp (along with a few others)- how can I help you?

**Comment by xamanu** [comment]
@KristenEgermeier Is there a general HOT newsletter we would like people to be able to subscribe through the website?

**Comment by KristenEgermeier** [comment]
@xamanu We are actually working towards a newsletter but it's not currently ready yet.  I think a subscription through the website in the future would be great.  I just don't want people to think that they are going to get one right away.  I hope to have one within a few months though.  
I don't think we want to ping everyone, every time we have a new website update, that might be too much.  Our newsletter will probably only be monthly.

**Comment by xamanu** [comment]
@KristenEgermeier ok, great! Just let us know, when you have the newsletter set up (and a team behind it) and we can easily integrate mailchimp on the website, so that people can easily subscribe.

**Comment by KristenEgermeier** [comment]
@xamanu Perfect, thanks so much!

**Comment by xamanu** [comment]
@KristenEgermeier suggested to add a newsletter sign up. It would be good to know how you want this to work. Right now I could think about:

* Mailchimp integration (we mentioned this before)
* Email notifications every time a person subscribes to it. The list must be maintained manually.
* Some more to the website integrated functionality, like sending newsletters from the website directly based on the articles, etc.

**Comment by KristenEgermeier** [comment]
This came up in the CWG last week.  I think we were hoping for a mail chimp integration.  Right now we wanted to just get the idea down. If there is a sign up on our website, it reaches an audience we might not reach through FB/ Blogs etc.  If they can sign up directly from there, that would be great.

**Comment by xamanu** [comment]
I would need the mailchimp API key for the account. Get or generate a valid API key at the Mailchimp API dashboard http://admin.mailchimp.com/account/api and send it to me privately. 

Thank you!

**Comment by xamanu** [comment]
Grace provided me the API key. We now have a third button link in the footer to the form to subscribe to the Newsletter. Please check and give feedback, if all is good.

**Comment by xamanu** [comment]
@TylerRadford and Grace confirmed me via email that is working all good and the first newsletter has been sent a couple of hours ago. Yeah! Thanks to everybody involved. Closing here.
