### ISSUE TITLE
Font / formatting issues on the migrated blogs (and possibly other text)

### ISSUE THREAD

**Issue by RebeccaFirthy** [hotosm/hotosm-website#247]
Example: http://www-dev.hotosm.org/projects/legit_supporting_decentralization_in_liberian_cities - font in Calibri

**Comment by RebeccaFirthy** [comment]
@smit1678 tagging you just in case i put this in the wrong place..

**Comment by smit1678** [comment]
👍 this was fixed for some of the more recent blogs but some issues remain on older blog posts.
