### ISSUE TITLE
Video section (related to projects)

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#25]
Taken from: https://github.com/hotosm/hotosm/issues/11

A section with a content type for videos and views to show them on the related places is requested by @mikelmaron to be implemented.

As far the first step has been done. The content type has been created and it would be good to have some videos to be integrated: http://hotosm.org/node/add/video

This would be good to have in order to then theme it nicely and put the right views in place.

@mikelmaron, do we have enough videos to use already? Can you create them, please? Or provide some links to youtube, where these are hosted. Thanks!

**Comment by xamanu** [comment]
I proposed this to the communications wg, but no answer about this. Looks like there is not a big interest in using videos on the website :( I will give it another try and mention it on the next meeting, if nothing is going to happen I'd suggest to disable this functionality.

**Comment by russdeffner** [comment]
I think this is longer term site improvements - there was a lot on the agenda for the group (and some confusion about immediate enhancement vs. longer term site design.  I would keep the functionality around until we get a solid long-term plan.

**Comment by xamanu** [comment]
I'm closing this. In different occasions the communications working group has not responded to any request if there are any videos. We don't have to think about this if there are no videos, nor people who want to nourish such a section.
