### ISSUE TITLE
Anchor link for GIS Professional on "Get Involved"

### ISSUE THREAD

**Issue by vannicer** [hotosm/hotosm-website#277]
Not high priority, but anchor link on Get Involved page for GIS Professional actually goes below that title (title not visible)

**Comment by uimarshall** [comment]
@ramyaragupathy please can i work on this issue?

**Comment by ramyaragupathy** [comment]
Sure @uimarshall! - Link for software engineers highlights the content and the title. Similar to Software Engineers - Mapping Volunteers & GIS Professionals should be highlighted along with the title in view.


### Anchor link for sotware engineers appear with the title in view
![anchor link](https://user-images.githubusercontent.com/12103383/54527695-aeeeee80-49a0-11e9-96b4-42decc0e07c3.gif)


### Highlight title for GIS Professionals & Mapping Volunteers
![anchor link-2](https://user-images.githubusercontent.com/12103383/54527694-aeeeee80-49a0-11e9-8314-30ee985b1f76.gif)

**Comment by uimarshall** [comment]
@ramyaragupathy thanks

**Comment by uimarshall** [comment]
@ramyaragupathy ,how do i get the `link` to the issue?

**Comment by uimarshall** [comment]
@ramyaragupathy ,Please who do i navigate to the folder where the issue is, after cloning the repo? am stuck here.

**Comment by Muskan284** [comment]
@ramyaragupathy @vannicer  can i also work on this issue?

**Comment by richa208** [comment]
@uimarshall I think the files `/_layout/get-involved.html` and `/volunteer.markdown` would be related to this issue.

**Comment by richa208** [comment]
A similar behaviour is seen if we select `Media Kit` link from the footer.

![hot8](https://user-images.githubusercontent.com/25206394/54934198-19c19c00-4f44-11e9-8408-b7753a26134b.gif)

@vannicer @ramyaragupathy As this issue has not been resolved yet, can I work on it?

**Comment by Muskan284** [comment]
@richa208  i have asked for this issue earlier and solved the issue for the get involved page .I am sending pr in a bit

**Comment by ramyaragupathy** [comment]
Fixed through #511
