### ISSUE TITLE
Map link metadata field on Country pages isn't displayed/exposed

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#278]
Map link metadata field on Country pages isn't displayed/exposed

**Comment by TylerRadford** [comment]
![image](https://user-images.githubusercontent.com/9853903/41292447-9d42eefe-6e20-11e8-9a1e-396d02774fc1.png)

I assume the "Map Link" field refers to the office location's address.
But after entering a URL here, I don't see it exposed anywhere. I would expect it to show up on the map in the header or on the right side under "Visit".
![image](https://user-images.githubusercontent.com/9853903/41292541-e0c2d0fe-6e20-11e8-9696-2a7d6d429dcf.png)

**Comment by uwaiszaki** [comment]
@ramyaragupathy @smit1678 I have created a pr for this issue #418.
