### ISSUE TITLE
Bullets and numbers don't display properly

### ISSUE THREAD

**Issue by RebeccaFirthy** [hotosm/hotosm-website#279]
When trying to create numbered lists, they appear as bullets. They also appear in black (rest of text is grey), and I can't seem to create space after the list. Screenshots from website and siteleaf attached.

![screen shot 2018-06-08 at 15 52 49](https://user-images.githubusercontent.com/25038632/41182159-1922a8d2-6b3a-11e8-97e1-7f60b4a300c9.png)
![screen shot 2018-06-08 at 15 52 54](https://user-images.githubusercontent.com/25038632/41182172-203b3e04-6b3a-11e8-90e3-f8105a9d4d8c.png)

**Comment by smit1678** [comment]
@RebeccaFirthy Yeah if you put a line between numbers, then this should work. Something like: 

```
1. item 1

2. item 2

3. item 3
```

@brendangatens is there a way to factor for both of these scenarios? I think the reasoning is that Siteleaf puts in a `<p>` tag in one of the scenarios and we're only styling that one?
