### ISSUE TITLE
Rethink second level navigation

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#29]
When visiting the "About", "Leadership" or "Get involved" sections we have a second level navigation menu on the right side as a block.

Let this issue to be used to see if we can/want to improve this. Alternatives, I have in my head, could be a drop down navigation or a second line under the first level navigation. Both are generally more intuitive for visitors and would not take so much space away than a whole sidebar.

Opinions?

**Comment by xamanu** [comment]
A basic implementation of the second level menu can now be reviewed on the staging site: http://hotosm.mapanica.net/about

**Comment by xamanu** [comment]
Done.

**Comment by russdeffner** [comment]
So @xamanu - please double check the capitalization on the second level menu; example: on the Get-Involved page, it currently reads "Emergency Mapping _ Working groups _ Jobs" - should capitalize "Groups" - think I saw another case of this somewhere else too.

**Comment by xamanu** [comment]
Thanks, @russdeffner! I changed this and also "Voting Members".
