### ISSUE TITLE
OpenStreetMap Sierra Leone page - 404 error

### ISSUE THREAD

**Issue by vannicer** [hotosm/hotosm-website#300]
http://www-dev.hotosm.org/projects/openstreetmap-sierra-leone/

**Comment by smit1678** [comment]
@vannicer Where did you click this link from? I can't find this as a project.

**Comment by vannicer** [comment]
@smit1678 pulled from "complete page listing" spreadsheet we've been working off of.

**Comment by smit1678** [comment]
Ah ok thanks. It looks like it was deleted: https://github.com/hotosm/hotosm-website/commit/f5661db594685d23a9b5cba04f6cb8cad7d7a488. And I didn't update the content list so this should be ok for now.
