### ISSUE TITLE
Set up staging site

### ISSUE THREAD

**Issue by ifrik** [hotosm/hotosm-website#31]
If we work with several people we need an additional staging site to test commits, and to allow other to see whether the proposed change solves the issue before pushing it to the production site.

**Comment by xamanu** [comment]
There is a VPS I don't use - I got it as a present six years ago at a DrupalCon and it will be free forever :) At least this is what they told me....

I have no problems giving access to this server to people working on the project, as no other data is on it. Let's just use this for now. Maybe @dodobas wants to give it a nicer domain name (dev.hotosm.org or stage.hotosm.org or something link that, the IP is below).

Domain: http://hotosm.mapanica.net
IP: 216.119.148.151
User/password: hotosm (both)

The password is no security, it is just to make sure no crawler/search engine get's it.
Please send me a public SSH key and I can give access.

**Comment by dodobas** [comment]
so we have a dev.hotosm.org subdomain... on which I've added www.dev.hotosm.org A record that points to your server, is that ok?

**Comment by xamanu** [comment]
Perfect! Thank you, @dodobas.
