### ISSUE TITLE
Impact area page: countries on map don't match countries on projects

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#324]
https://www.hotosm.org/impact-areas/refugee-response/
Only Turkey and Uganda are shaded on the map on the top of page
I expected to also see South Sudan, Syria, and France shaded in the map

![image](https://user-images.githubusercontent.com/9853903/41613365-6246603a-73c3-11e8-93ed-8945fc1a59ee.png)

**Comment by smit1678** [comment]
@TylerRadford We'll need to tag those projects with those countries, I suspect those projects are not tagged with those countries.

**Comment by smit1678** [comment]
Quick follow up, projects are tagged with Syria and South Sudan as countries and so there is another issue at play here that we need to investigate.

**Comment by willemarcel** [comment]
Pushed a fix in https://github.com/hotosm/hotosm-website/pull/325
