### ISSUE TITLE
Reduce the number of countries shown on blog post preview

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#343]
<img width="1161" alt="humanitarian openstreetmap team home 2018-07-10 14-58-02" src="https://user-images.githubusercontent.com/796838/42514590-abff99dc-8451-11e8-9b4e-8db77fbda50d.png">

<img width="927" alt="humanitarian openstreetmap team news 2018-07-10 14-56-51" src="https://user-images.githubusercontent.com/796838/42514528-8af1a96a-8451-11e8-90e6-4a53e5a3310e.png">

**Comment by uwaiszaki** [comment]
hey , i would like to work on this issue.

**Comment by ramyaragupathy** [comment]
Awesome @uwaiszaki! Please go through a related PR https://github.com/hotosm/hotosm-website/pull/395, which is for reducing number of countries in news preview page

**Comment by uwaiszaki** [comment]
@ramyaragupathy I have created a pr for this issue, Please review it

**Comment by smit1678** [comment]
Fixed here, https://github.com/hotosm/hotosm-website/pull/414. Thanks @uwaiszaki for the contribution!
