### ISSUE TITLE
Country and Impact Area pages: Differentiate between Active/Completed projects

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#347]
Make some visual distinction between active and completed projects on the Country and Impact Area pages. For example: https://www.hotosm.org/where-we-work/central-african-republic/
We haven't worked in CAR in 4-5 years - we should be clear about this including where it says "Central African Republic has 2 projects"

**Comment by ramyaragupathy** [comment]
We're providing filters to distinguish active & archived projects:

![image](https://user-images.githubusercontent.com/12103383/54138165-f6c3c200-4444-11e9-9110-5fcc29591569.png)

On project cards we could include a `ACTIVE/COMPLETED` text depending on duration. This is similar to what is implemented in project pages

**Project Card:**
![image](https://user-images.githubusercontent.com/12103383/54138290-2bd01480-4445-11e9-959b-eb655dbc64da.png)

**Project Pages:**
![image](https://user-images.githubusercontent.com/12103383/54138354-4dc99700-4445-11e9-9b9b-04ecb6897918.png)

**Comment by sresthas** [comment]
Hey, I am an outreachy applicant, can I take this up?

**Comment by ramyaragupathy** [comment]
Sure go for it @twisted-sres

**Comment by sresthas** [comment]
Hey @ramyaragupathy @TylerRadford , please let me know the link to project pages and project card, I am new to this project so I don't know much about the site. Also, is it suggested to add anactive text on project card like project pages for this bug?

**Comment by nav-p** [comment]
@ramyaragupathy  I'm an outreachy applicant can i also work on this?

**Comment by bismitaguha** [comment]
@ramyaragupathy since this issue has not been worked upon till now, I am giving it a try.
