### ISSUE TITLE
Error on user page: Notice: Undefined index: title in field_extra_fields_get_display

### ISSUE THREAD

**Issue by harry-wood** [hotosm/hotosm-website#35]
What's wrong on this page? http://hot.openstreetmap.org/user/52

Currently showing the error "Notice: Undefined index: title in field_extra_fields_get_display() (line 682 of /var/www/modules/field/field.module)."  in a red box at the top

**Comment by ifrik** [comment]
I'm looking into it.

**Comment by xamanu** [comment]
I can't reproduce this (anymore). So closing, here...
