### ISSUE TITLE
Country page: Title placement

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/hotosm-website#359]
Country title is pinned to the map centroid. This is clumsy in case of a lengthier title as it hides the project circles. What could work is have the title moved to a corner when the tab switch is made for campaign filters. 

![image](https://user-images.githubusercontent.com/12103383/45495772-8c7ddd80-b791-11e8-9811-1862acc4435b.png)

**Comment by smit1678** [comment]
I'd like to suggest that we pin the title to the corner from the start. This will then match our other map views, like the Our Work page. Plus pinning to the corner on the first view then gives the chance for users to explore a bit more before selecting the campaign filters to explore more. 

<img width="1390" alt="Humanitarian OpenStreetMap Team | Tanzania 2019-03-11 14-51-26" src="https://user-images.githubusercontent.com/796838/54108042-7afa5300-440d-11e9-92c2-271baf63b541.png">

**Comment by uwaiszaki** [comment]
@ramyaragupathy @smit1678 I have created a pr for this [https://github.com/hotosm/hotosm-website/pull/417](URL).

**Comment by Jenniline** [comment]
Hi @ramyaragupathy would like to work on this

**Comment by ramyaragupathy** [comment]
@Jenniline - this issue is already been worked upon by @uwaiszaki. Please feel free to pick other items from the issue list. Also do keep an eye on #starter-issues in HOT slack group

**Comment by Jenniline** [comment]
Ok..Thanks @Ramya
