### ISSUE TITLE
Bad link on http://hot.openstreetmap.org/get-involved ?

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#36]
The section that reads:
HOT Separate OSM Data Store: A tool to store sensitive or non-OSM suitable data alongside the existing OSM dataset. 
is linked to:
http://datastore.hotosm.org/
I am not sure if that exists or is just down, but it doesn't respond.

**Comment by xamanu** [comment]
I wrote to the TechWG to ask about this.

**Comment by xamanu** [comment]
No answer from TechWG. So I took this one out of the text. Thanks for reporting!
