### ISSUE TITLE
Landing page: Unable to choose countries at the bottom of the map

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/hotosm-website#360]
![our-work](https://user-images.githubusercontent.com/12103383/45496070-3e1d0e80-b792-11e8-8e82-ac9f80a7dfcb.gif)

Div adjustment required

**Comment by uwaiszaki** [comment]
Hey , I would like to work on this issue.

**Comment by uwaiszaki** [comment]
@ramyaragupathy I have fixed this issue by adding pointer-events CSS in the map. Please review my pr [https://github.com/hotosm/hotosm-website/pull/416](url)

**Comment by ramyaragupathy** [comment]
Fixed through https://github.com/hotosm/hotosm-website/pull/416
