### ISSUE TITLE
Look at adding imgbot

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#369]
One method for automating some image compression on uploaded images (if someone forgets to resize or compress their images) is to leverage imgbot from the Github Marketplace. 

https://github.com/marketplace/imgbot

Let's consider adding as an option to help ensure that images are always compressed when uploaded.

**Comment by dakotabenjamin** [comment]
We should add this. 
Pro:
- contributors are not generally going to optimize their own images
- we shouldn't be doing it manually
- free

Cons: 
- Increases the size of the repo

Notes:
- Doesn't change actual image dimensions so wouldn't solve the issue with the participatory mapping toolkit page highlight image. 

The repo size issue isn't great but is a small issue, and we should absolutely be optimizing our images. I can install the bot and it will open a PR so we can see just how much we are reducing and optimizing.

**Comment by smit1678** [comment]
Bot installed, let's see how this works. 

<img width="776" alt="installed github app - imgbot 2019-01-16 10-30-56" src="https://user-images.githubusercontent.com/796838/51224739-e843b780-1979-11e9-862d-2a2aef255893.png">
