### ISSUE TITLE
Switch to Piwik for website stats

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#37]
To facilitate the sharing of our website stats, we would like to consider using Piwik to track traffic on the main HOT websites. One issue to consider is if the piwik stats would be fully public or restricted to just the HOT/OSM interested community.

**Comment by xamanu** [comment]
I use Piwik for most of my websites and it is a great tool. You can even be nice to your visitors and not save their IP addresses forever. And it is not a great thing to maintain it. The stats are not automatically public, this is a more political decision to make.

**Comment by xamanu** [comment]
@dodobas Would it be possible to set up a Piwik instance in some part of our nice server space?

**Comment by dodobas** [comment]
we already have it setup... piwik.hotosm.org ... this is the tracking code for the hotosm.org web

I would suggest to run both piwik and GA in parallel for a while 
```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//piwik.hotosm.org/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 5]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//piwik.hotosm.org/piwik.php?idsite=5" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
```

**Comment by xamanu** [comment]
I just added the code. Both, Piwik and GA, are active for now. Once we see stats coming in through Piwik we can disable GA. So leaving this open, until then.

**Comment by xamanu** [comment]
Seems to work properly: http://piwik.hotosm.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=5#/module=Dashboard&action=embeddedIndex&date=yesterday&period=day&idSite=5&idDashboard=1

Any reason why not to disable Google Analytics tracking, @dodobas? Or shall I proceed?

**Comment by russdeffner** [comment]
I would suggest if it isn't a problem to run both until next Tech WG meeting, then maybe a more 'formal' decision to disable GA.

**Comment by xamanu** [comment]
Not just, last tech meeting it was common sense in the techweg to switch over to Piwik. I've heard nobody arguing in favour of GA. So, why wait for one entire month? We just have to check if this is working and then we can switch it off in my opinion.

Please, let's get things done.

**Comment by xamanu** [comment]
As suggested I consulted the tech working group and got no objections. Google Analytics is now down and code removed.
