### ISSUE TITLE
Role removed to an existing account

### ISSUE THREAD

**Issue by pierzen** [hotosm/hotosm-website#38]
Discussion with Felix DeLattre. He says that I have no role to edit on hot.openstreetmap.org.  I wonder how I was able to write all the updates so  far.

Could somebody look at Account pierre dot beland and fix the role problem with this account?

**Comment by ifrik** [comment]
Done.
I think the problem was not that anybody removed your role, but that a change had been made with the permissions in general. You should be able to post again.
I leave this issue open to check whether it is a general problem

**Comment by pierzen** [comment]
Thanks

Edition acccessible again.

Was there any restructuring of roles?
