### ISSUE TITLE
Make HOT bylaws and Articles of Incorporation more easily visible

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#386]
https://www.hotosm.org/community/

There is a link here to HOT Bylaws under "Financials and Organization". Could we make this more visible/more easily accessible?

HOT mission, contained in our Articles of Incorporation is also missing a link.

**Comment by ramyaragupathy** [comment]
Addressed through https://github.com/hotosm/hotosm-website/pull/399
