### ISSUE TITLE
Privacy page missing

### ISSUE THREAD

**Issue by michael63-osm** [hotosm/hotosm-website#389]
The new banner introduced for the Matomo tracking code (#387) (https://github.com/hotosm/learnosm/pull/563) refers to https://hotosm.org/privacy for information about our privacy policy. However this results in a 404 error. Either we can come up with this page quickly or we should remove this link from the tracking code.

**Comment by smit1678** [comment]
Thanks @michael63-osm, we're waiting for a final version which is being tracked here: https://github.com/hotosm/legal/pull/1. Once we have the final version ready, we'll then add a simple /privacy page with the text and link to the source repo.
