### ISSUE TITLE
Language pop down menu does pop down for selection

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#40]
When I try to use the language pop down menu, I can never get it to pop down so there is no way for me to select another language. Tested on win7 FF, Chrome, and MacOS FF, Chrome, Safari

Edit: The pop down does work if I go to a non existent page and get the 404 page or if I am on any of the French pages, I can select English or French, but once I am on the regular English pages, the pop down stops working.

**Comment by xamanu** [comment]
Related to #32

**Comment by xamanu** [comment]
Fixed. The language dropdown should now work. Thanks for reporting!
