### ISSUE TITLE
Add jobs to search

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/hotosm-website#412]
Currently the search indexes posts, people, and projects. Adding jobs as well would make it easier to get to them. 

You can do that by adding a new item to the list in `search.json`. The format should be the same as the other items. There should be a conditional block as well to not include closed positions.

**Comment by bismitaguha** [comment]
`{% for jobs in site.jobs %}
{
"type":"Jobs",
"title":"{{ jobs.title | escape }}",
"summary":"{{ jobs.body | escape | truncatewords: 40 | strip | prepend: ' ' }}",
"subtitle":"{{ jobs['Job Description'] | join: ', ' }}",
"url":"{{ site.url }}{{ jobs.url }}",
"date":"{{jobs.date }}"
} {% unless forloop.last %},{% endunless %}
{% endfor %}`

I thought of the following code. Please mention your reviews on this

**Comment by bismitaguha** [comment]
I have made a Pull Request.
Waiting for your review.

**Comment by Jenniline** [comment]
Hi @ Can i work on this issue? Or be assigned a task?

**Comment by bismitaguha** [comment]
I am continuing to work on this issue @dakotabenjamin .

**Comment by dakotabenjamin** [comment]
Fixed in #465
