### ISSUE TITLE
No. of countries in news preview page.

### ISSUE THREAD

**Issue by uwaiszaki** [hotosm/hotosm-website#415]
Should we add a dropdown to display the list of remaining countries?
![hotosmnewissue1](https://user-images.githubusercontent.com/32809190/54071898-3ea5e600-4299-11e9-99ae-ecaa69ab7c4f.png)

**Comment by uwaiszaki** [comment]
If yes I would like to work on this issue.

**Comment by ramyaragupathy** [comment]
Dropdown is not required for country listing here @uwaiszaki.  Just the changes in https://github.com/hotosm/hotosm-website/pull/395 should be sufficient
