### ISSUE TITLE
hotosm.org shortlink?

### ISSUE THREAD

**Issue by jeffhaack** [hotosm/hotosm-website#42]
I am wondering if it would be possible to create a shortlink from the hotosm.org domain for our project in Dar es Salaam.  The idea would be to have a shortlink for the project, hotosm.org/RamaniHuria, which would redirect to OpenStreetMap over Dar <http://www.openstreetmap.org/#map=13/-6.8098/39.2739>.  Would this be doable?

**Comment by xamanu** [comment]
This is doable. But nothing like this has done before. And such links seems to me, more like a page on the website, and not a redirect.

**Comment by xamanu** [comment]
I would give it a "won't fix". As this would be a new functionality, which nobody else has said he/she needs and it confuses people as they would expect to land on the hot website and end up on osm.
Leaving this open here, so other people can give their opinion.

**Comment by jeffhaack** [comment]
I can understand that, and it makes sense to me.  Thanks!

**Comment by xamanu** [comment]
Thank you @jeffhaack 
And please feel free to provide other suggestions for the website in the future.
