### ISSUE TITLE
Improve author list formatting in news aggregation for project pages

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/hotosm-website#421]
Each project page has news aggregation related to the project and the filtered items are placed right above the page footer. 

News items listed here could have better formatting of author list. Highlighted a few in the screenshot where we should:
- Allow a  Comma-separated Author list
- Handle empty author fields

![image](https://user-images.githubusercontent.com/12103383/54186781-28369f00-44d2-11e9-9717-5381320f44cc.png)

**Comment by uwaiszaki** [comment]
Hey @ramyaragupathy, I am working on this issue.

**Comment by uwaiszaki** [comment]
@ramyaragupathy I claimed this issue before her. Please review my pr #424

**Comment by Jenniline** [comment]
Hi @ramyaragupathy  I am Jenniline an Outreachy applicant can i work on this? Or have a task assinged to me?
