### ISSUE TITLE
Overlapping in Tools and Data Page

### ISSUE THREAD

**Issue by sresthas** [hotosm/hotosm-website#425]
Tools and Data Page looks like this on my system as well as on localhost
![Screenshot from 2019-03-14 01-54-48](https://user-images.githubusercontent.com/36242614/54312462-0e45ab00-45fd-11e9-84bc-32bb180c635b.png)

**Comment by sresthas** [comment]
@ramyaragupathy @smit1678 Please look into this

**Comment by ramyaragupathy** [comment]
Layout work needed. There's an overlap of body and the footer.

![image](https://user-images.githubusercontent.com/12103383/54330086-664ed280-463a-11e9-8525-812fe538b8ff.png)

@twisted-sres - would you like to work on this issue fix?

**Comment by sresthas** [comment]
Yeah, sure. On it.:)
