### ISSUE TITLE
Carousel buttons are not disabled

### ISSUE THREAD

**Issue by richa208** [hotosm/hotosm-website#426]
While viewing the carousel on home page, the forward and backward buttons should become disabled for clarity if there are no more images available.

![hot](https://user-images.githubusercontent.com/25206394/54356214-121b1100-4681-11e9-9c7b-e579b0b6a48c.gif)

**Comment by richa208** [comment]
@ramyaragupathy  If the issue seems appropriate, I would like to work on it.

**Comment by ramyaragupathy** [comment]
sure, go for it @richa208
