### ISSUE TITLE
No links attached and overlapping content in main page 

### ISSUE THREAD

**Issue by Muskan284** [hotosm/hotosm-website#427]
@ramyaragupathy  there is overlap in content of main page also down below the page there are tags like openstreetmap foundation, OSM wiki,local community discussions which when clicked do nothing.Where these tags meant to link to any other page?

![Screenshot from 2019-03-14 18-41-35](https://user-images.githubusercontent.com/42279758/54360014-dfc1e180-4689-11e9-955d-e0d8383b5c9b.png)

**Comment by Muskan284** [comment]
@ramyaragupathy can i work on this ?

**Comment by ramyaragupathy** [comment]
Thanks for flagging the issue @Muskan284! Feel free to work on a fix. Do drop a comment letting people know that you are already working on a fix.

Attaching a screenshot of the entire page for reference
![image](https://user-images.githubusercontent.com/12103383/54361513-27963800-468d-11e9-8859-1377919bb475.png)

**Comment by ramyaragupathy** [comment]
Also @Muskan284 - suggest you finish this fix, before moving on to other issues. Thank you!

**Comment by Muskan284** [comment]
sure @ramyaragupathy , will take care of that. I am working on this issue.

**Comment by bismitaguha** [comment]
Fix #427.
@ramyaragupathy 
I tried working on the issue, and could remove the overlapping texts and the links are working too.
Please review the PR. Waiting for your suggestions

**Comment by ramyaragupathy** [comment]
@codefab99 - Thanks for taking the time to look at this. However, from the earlier comments, it is clear @Muskan284 already claimed this. So I am considering @Muskan284's PR here. Please feel free to work on other issues & suggest you pick one issue at a time to work on.
