### ISSUE TITLE
Handling empty field in Project Pages

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/hotosm-website#428]
There are projects with empty metadata fields. In such cases, these field names need not be shown at all.
![gf](https://user-images.githubusercontent.com/12103383/54363667-5c0bf300-4691-11e9-95f0-2e522f50fcb1.png)

**Comment by richa208** [comment]
Can i work on this?

**Comment by bismitaguha** [comment]
@ramyaragupathy I am working on this.

**Comment by richa208** [comment]
Hi @codefab99 
I claimed this issue before you and had started working on this too. Kindly work on some other issue which is not claimed by anyone. Thanks :smiley:
