### ISSUE TITLE
board members page is outdated

### ISSUE THREAD

**Issue by pgiraud** [hotosm/hotosm-website#43]
http://hotosm.org/our_board

**Comment by jaakkoh** [comment]
A quick fix has been made. More content needed from board members (bios, photos).

**Comment by xamanu** [comment]
Thanks @jaakkoh. Just to connect the tickets: soon we should have the contents pulling directly from the user's profiles, #20 
Cheers

**Comment by xamanu** [comment]
I got photos for all board members. Only the bio texts for Blake and Jorieke are missing. 
You can also check the new board view (in progress) as a logged-in user: http://hotosm.org/leadership/board

**Comment by russdeffner** [comment]
Looking great, I can reach out to Blake and Jorieke about bios.

**Comment by xamanu** [comment]
@russdeffner any news from Blake and Jorieke? Still no text online in the board view: http://hotosm.org/board Thank you!

**Comment by russdeffner** [comment]
I will write an email to the membership after the meetings today - asking for everyone to update their profiles, as well as some of the other issue needs.

**Comment by russdeffner** [comment]
I think we could close/merge this with https://github.com/hotosm/hotosm-website/issues/60 - am I correct that the Board page will now populate with user profile that have the 'Board Role' set?

**Comment by xamanu** [comment]
yes! Closing here. Thanks!
