### ISSUE TITLE
Handle duration field better

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/hotosm-website#430]
Handle empty `Start Date` better.  State should be just `Ongoing` instead of `- Ongoing`
![image](https://user-images.githubusercontent.com/12103383/54364365-c5403600-4692-11e9-9aac-fcfd4d3a2148.png)

**Comment by Muskan284** [comment]
@ramyaragupathy  i am working on this.

**Comment by vatsalanarang** [comment]
@ramyaragupathy I am an outreachy aspirant and want to work on this issue if its not assigned ,please assign it to me.

**Comment by ramyaragupathy** [comment]
@vatsalanarang - From the previous comment looks like @Muskan284 has already begun work on this.     Please go through our issue list for other fixes. Thank you!
