### ISSUE TITLE
Screenshot and overlapping divs in what-we-do, our-work and tools-and-data pages

### ISSUE THREAD

**Issue by bismitaguha** [hotosm/hotosm-website#432]
The placing of divs in these pages and the complete css is causing lots of overlapping data. Some divs are placed on the margins of other divs and extra divs named 'block-screenshot' and 'block-screenshot-wrap' and created which have no content and are just created to adjust padding and margins. Considering healthy contributor practices this is a major issue as such overlaps should be removed which will avoid redundant code and long css. I would like to work on this issue considering remaking the divs without changing the structure of pages.
@smit1678 @dakotabenjamin @ramyaragupathy  Please consider this. I would like to work on this and I feel the code will get a proper structure if we onsider this issue thus making it suitable for developers referring to HOTOSM's code.
![IMG_20190315_024318](https://user-images.githubusercontent.com/43119923/54392303-4ddbc800-46cd-11e9-83cc-bdbd011fe87c.jpg)

**Comment by ramyaragupathy** [comment]
@codefab99 - Can you attach a screenshot of the issue here please? What you describe seems familiar with the issues raised https://github.com/hotosm/hotosm-website/issues/425, https://github.com/hotosm/hotosm-website/issues/427. Attaching a screenshot would just make it clear

**Comment by ramyaragupathy** [comment]
Fixed through https://github.com/hotosm/hotosm-website/pull/454
