### ISSUE TITLE
 Increase social link icons, correct button Donate and get involved

### ISSUE THREAD

**Issue by gellys** [hotosm/hotosm-website#434]
- Social link icons need to be bigger.
- The donate button does not darken like the others, need to add the same effect
- The Get Involved button has a color that the user can mean as disabled.

I'd like to work on it. Can I start?

![outreachy-siteosm01](https://user-images.githubusercontent.com/27901470/54395365-6a0c4480-468e-11e9-811d-53bbcec47f04.PNG)

**Comment by ramyaragupathy** [comment]
Can you please attach a screenshot/gif of your proposal before we decide here? Here's a link to our website logos & image guidelines: https://github.com/hotosm/hotosm-website/wiki/Colors-Fonts-and-Logo

Try incorporating these in your ideas.

**Comment by gellys** [comment]
Of course yes. I'll finish here my idea.

**Comment by richa031** [comment]
@ramyaragupathy .Is this issue still open to work upon?

**Comment by ramyaragupathy** [comment]
Stale
