### ISSUE TITLE
No mailto in the 'href' attribute on the contact page

### ISSUE THREAD

**Issue by bismitaguha** [hotosm/hotosm-website#435]
Clicking on any mail-id on the contact page gives error this is because the 'href' attribute does not have "mailto:" attached to it. I would like to work on this issue.
@smit1678 @ramyaragupathy @dakotabenjamin Please approve this as an issue.

**Comment by ramyaragupathy** [comment]
Sure - go ahead, but please make sure to fix the already claimed job search issue https://github.com/hotosm/hotosm-website/issues/412 before you begin work here.

**Comment by bismitaguha** [comment]
Ok. I am currently working on this issue. #435
