### ISSUE TITLE
Admin email for website

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#44]
Hello,

I just saw, in the website for the admin account and the global site's email address there are different private email addresses. I would suggest to have a special email address for the website, something like admin@hotosm.org or webmaster@hotosm.org

The best would be to have it redirected to the techWG email list, or to the one's that are assuming the role of the admin.

Thank you

**Comment by xamanu** [comment]
I talked with @jaakkoh today about this. He wanted to look into that.

**Comment by xamanu** [comment]
@jaakkoh, any news on that?

**Comment by wonderchook** [comment]
@KristenEgermeier is the email admin and could make a new email address to redirect if needed.

**Comment by xamanu** [comment]
Thanks @wonderchook! I wrote @KristenEgermeier an email, directly.

**Comment by xamanu** [comment]
ok, thank you @KristenEgermeier for setting this up! The general website's email address is info@....(as the general input channel) and the main admin account is now connected to webmaster@.... which is a list and people (tech wg, etc.) can request to be one of the receivers.
