### ISSUE TITLE
The footer icon of HOTOSM on click should go to home page

### ISSUE THREAD

**Issue by bismitaguha** [hotosm/hotosm-website#443]
The icon on the footer is non-clickable. It should redirect to home page.
@ramyaragupathy @dakotabenjamin @smit1678 If this is a considerable I would like to work on it.
Please provide suggestions.

**Comment by uimarshall** [comment]
I am an outreachy applicant, i want to find out if i can work on this issue.

**Comment by ramyaragupathy** [comment]
@uimarshall - Thanks for looking at our issue list. @codefab99 is already working on this. Please feel free to pick other issues.

**Comment by uimarshall** [comment]
@ramyaragupathy, i find out most of the issues have been assigned, kindly assign one for me.

**Comment by bismitaguha** [comment]
@ramyaragupathy please check my PR. #445
