### ISSUE TITLE
handle tool field better

### ISSUE THREAD

**Issue by Muskan284** [hotosm/hotosm-website#446]
Not all projects utilize some tools .Tools option  should be present in only those project pages which  utilize some tools
![Screenshot from 2019-03-16 09-59-21](https://user-images.githubusercontent.com/42279758/54470685-4fdb7f00-47d2-11e9-99f0-bcc361ae2a57.png)
@ramyaragupathy  i would like to work on this issue.

**Comment by bismitaguha** [comment]
#436 this issue is solved.
