### ISSUE TITLE
handle data field better

### ISSUE THREAD

**Issue by Muskan284** [hotosm/hotosm-website#447]
Not all projects have data related to it @ramyaragupathy i would like to work on this issue.
![Screenshot from 2019-03-16 09-59-21](https://user-images.githubusercontent.com/42279758/54470722-ec9e1c80-47d2-11e9-8aee-17d60932a31b.png)

**Comment by ramyaragupathy** [comment]
Already addressed through https://github.com/hotosm/hotosm-website/issues/428 &  https://github.com/hotosm/hotosm-website/pull/436
