### ISSUE TITLE
Text is outside box in News Page

### ISSUE THREAD

**Issue by darshanv6** [hotosm/hotosm-website#448]
In the News page, the Subscribe for Updates & Announcements comes out of the red background and it will look better if it is inside it. 

![image](https://user-images.githubusercontent.com/21688871/54473376-03596900-47fd-11e9-94d7-d960e36b01cd.png)

A similar issue is present in the 'Page Not Found' page as well where the text '404 Page Not Found' text exceeds the red background. 

![image](https://user-images.githubusercontent.com/21688871/54473646-88924d00-4800-11e9-99d1-0c2d3a040606.png)

Shall I go ahead with the edit or is it how the text was meant to be?

**Comment by uimarshall** [comment]
@darshanv6 ,I am an outreachy applicant, i want to find out if i can work on this issue?

**Comment by ramyaragupathy** [comment]
This comes with the design @darshanv6 @uimarshall - nothing to update here!
