### ISSUE TITLE
Modifications in minimised screen

### ISSUE THREAD

**Issue by richa208** [hotosm/hotosm-website#451]
When the window is minimised following modifications can be done:
- change the cursor property on the hamburger icon from default to pointer
- change the alignments of hyperlinks on the footer from left to centre to make it a better UI

**Comment by richa208** [comment]
@ramyaragupathy If the modifications are appropriate, I would like to work on it.

**Comment by ramyaragupathy** [comment]
@richa208 - I don't get the complete context here. Can you please elaborate on this behavior? Adding a few screenshots/gifs will help.

**Comment by richa208** [comment]
When the window is minimised, currently the cursor property on the hamburger icon is default but it should be a pointer as it is a clickable option.

![54361649_2123920571049230_3616026450760564736_n](https://user-images.githubusercontent.com/25206394/54518838-4ba69180-498b-11e9-9011-810d3987afc8.jpg)


Also currently the footer content is left aligned. Making it centre aligned would improve the UI in my opinion. 

![54518471_338540503452753_6985110849144750080_n](https://user-images.githubusercontent.com/25206394/54518855-4e08eb80-498b-11e9-9e96-8b9a6ef804ed.jpg)

@ramyaragupathy Kindly suggest if the these modifications are appropriate.
