### ISSUE TITLE
Create page showing list of countries where Hotosm works

### ISSUE THREAD

**Issue by darshanv6** [hotosm/hotosm-website#452]
When a user goes to a specific country's page to see what HOTOSM has worked on in that country, he/she encounters a page like this. 

![image](https://user-images.githubusercontent.com/21688871/54495970-b87c4600-490f-11e9-8b0d-cf82d3bc4a54.png)

If he/she removes the country's name from the URL expecting to see the list of all countries in which HOTOSM works, he/she sees this page. 

![image](https://user-images.githubusercontent.com/21688871/54495986-f5e0d380-490f-11e9-94d5-8054dc9618ad.png)

From a UX perspective, it is better to show a page here which lists all countries in which HOTOSM works. @ramyaragupathy Can I go ahead and create a new page for this purpose?

**Comment by ramyaragupathy** [comment]
Hi @darshanv6 - we already have a `Our work` page with a map view of all countries that we work with.

![image](https://user-images.githubusercontent.com/12103383/54506433-6adcf900-4962-11e9-8368-8beeced15c9d.png)

May be we can redirect the https://www.hotosm.org/where-we-work/ link to https://www.hotosm.org/our-work page.

**Comment by darshanv6** [comment]
I'll work on this.
