### ISSUE TITLE
Country name is fixed on map irrespective of current location

### ISSUE THREAD

**Issue by richa208** [hotosm/hotosm-website#453]
While viewing any particular country to see the details in `Our Work`, the name of the country remains fixed on the map even if we drag the map to some other country.

![hot1](https://user-images.githubusercontent.com/25206394/54508257-56512e80-496b-11e9-8fb9-4f74d1b425e3.gif)
@ramyaragupathy @smit1678 I would like to remove this error.

**Comment by ramyaragupathy** [comment]
In this case we shouldn't allow panning the map through drag function. Please refer to https://docs.mapbox.com/mapbox-gl-js/api/#dragpanhandler documentation to see how to disable this behavior.
