### ISSUE TITLE
Unwanted text on Images - What-we-do page

### ISSUE THREAD

**Issue by VarunBhandia** [hotosm/hotosm-website#457]
![Screenshot from 2019-03-18 23-35-18](https://user-images.githubusercontent.com/27995669/54552671-aaddc380-49d6-11e9-8b9a-3d89132d671e.png)
@ramyaragupathy the text is coming on the image which looks bad for any user. 
Link => https://www.hotosm.org/what-we-do

**Comment by richa208** [comment]
Hi @VarunBhandia 
PR #454 already addresses this issue.

**Comment by VarunBhandia** [comment]
Ok ma’am

**Comment by ramyaragupathy** [comment]
Duplicate of https://github.com/hotosm/hotosm-website/issues/432, https://github.com/hotosm/hotosm-website/issues/425
