### ISSUE TITLE
Donate.hotosm.org

### ISSUE THREAD

**Issue by vannicer** [hotosm/hotosm-website#458]
Need a redirect back to donate.ly-embedded form page for Donate.hotosm.org and donate buttons

**Comment by Muskan284** [comment]
@ramyaragupathy @vannicer can i work on this issue?

**Comment by vannicer** [comment]
Yes, please! We should still have the embeddable form @smit1678 ?

**Comment by Muskan284** [comment]
@vannicer can u please elaborate this issue more?where the redirect links and buttons are placed exactly?

**Comment by vannicer** [comment]
so  http://donate.hotosm.org currently links to a CauseVox page but we'd like it to go to an embedded from from donate.ly as we had it prior to the 2018 Year-End Fundraising campaign

**Comment by smit1678** [comment]
I've changed this on our AWS account. It may take up to 24 hrs for it to fully change over depending on location, but should be working soon. 

> @ramyaragupathy @vannicer can i work on this issue?

@Muskan284 Apologies but this needed a fix on our AWS account only.

**Comment by vannicer** [comment]
I'm getting a 404, but I'll check on it again later. Thanks!

**Comment by smit1678** [comment]
You're right that was an error on the website's part -- was not handling `/donate/` which AWS was forwarding to (not sure why). But I've fixed this on the site: `https://www.hotosm.org/donate/` & `https://www.hotosm.org/donate` now work.

**Comment by vannicer** [comment]
All good, now, yeah thanks!
