### ISSUE TITLE
Cannot upgrade packages on hotwww server

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#46]
Hi @dodobas, can you please help me out. I just wanted to do simple apt-get upgrade (as root) but it fails here:

```
Setting up initscripts (2.88dsf-41+deb7u1) ...
mount: permission denied
```

Thank you!

**Comment by xamanu** [comment]
Just a note to myself: When this is done I shpuld not forget to install the PECL uploadprogress and check the OpenID Math library (issues from the drupal status page)

**Comment by dodobas** [comment]
hotwww is a real 'server' so there might be issues, I can upgrade/install new packages just give me a list of things to install

**Comment by xamanu** [comment]
In the first place it is just to do a regular package upgrade (apt-get upgrade) and make sure it runs properly and then install the "cron" package. Thank you!

**Comment by xamanu** [comment]
Still the same problem here. I can't upgrade/install new packages. @dodobas, any idea?

**Comment by xamanu** [comment]
I mentioned this at the last TechWG meeting. @dodobas is going to look for it (thanks!!!)

**Comment by xamanu** [comment]
The problem seems to be described here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=633845

**Comment by xamanu** [comment]
@dodobas Could you please look into this? It's not recommendable to have a server we can not maintain up to date.

**Comment by smit1678** [comment]
Closing this out as we've moved to a Github hosted Jekyll site.
