### ISSUE TITLE
handle pop up in donate page

### ISSUE THREAD

**Issue by Muskan284** [hotosm/hotosm-website#461]
when donate now option is clicked and any field is empty in donate page .the pop up appears but on scrolling the page the pop up also scrolls.
@ramyaragupathy  i would like to fix it.
![Peek 2019-03-19 14-35](https://user-images.githubusercontent.com/42279758/54593410-84f70400-4a54-11e9-9bcf-be1e98235254.gif)

**Comment by richa208** [comment]
@Muskan284 Also I think this issue is Firefox specific as it is working fine in Chrome.
It must be related to `type="email"` and firefox IMO.

**Comment by Muskan284** [comment]
Thanks @richa208
