### ISSUE TITLE
Person profile getting overlapped on map

### ISSUE THREAD

**Issue by ananya** [hotosm/hotosm-website#468]
Person's profile is covering the map on the www.hotosm.org/people/mhairi-ohara/ page.
According to the existing design i should come under the map

Current page:
![Screenshot from 2019-03-20 01-50-56](https://user-images.githubusercontent.com/33188930/54639449-6542f880-4ab3-11e9-9a87-bfd5e806ab77.png)

Other pages on website:

![Screenshot from 2019-03-20 01-54-45](https://user-images.githubusercontent.com/33188930/54639411-4e040b00-4ab3-11e9-9d9d-01238c403fcc.png)

If this is really a bug, then I would like to work on this.

**Comment by ramyaragupathy** [comment]
Expected behaviour - not a bug
