### ISSUE TITLE
Redirecting /people/ to /community/

### ISSUE THREAD

**Issue by darshanv6** [hotosm/hotosm-website#470]
When a user goes to a specific person's page, he/she encounters a page like this, with details of the person. 

![image](https://user-images.githubusercontent.com/21688871/54641287-d8e70480-4ab7-11e9-9de8-4c74ca1affaa.png)

If the name of the person is removed from the URL, we get error 404. I think it'll be better if we will be able to redirect that URL to /community#people by creating a new section called people in the Community & Organization page. 

@ramyaragupathy, can I go ahead with this?

**Comment by uwaiszaki** [comment]
@darshanv6 Removing name from URL does not give 404. It shows the index of /people/

**Comment by darshanv6** [comment]
@uwaiszaki the index of people is shown when it is run locally. In the website (hotosm.org/people) , 404 is returned.
