### ISSUE TITLE
hover effect missing in playground page

### ISSUE THREAD

**Issue by Muskan284** [hotosm/hotosm-website#476]
hover effect is missing in the box group header section of playground page.
@ramyaragupathy  presence of hover effect will have a better user experience . I would like to fix this problem.
![hover1](https://user-images.githubusercontent.com/42279758/54667999-cef2ef00-4b13-11e9-9d66-673c0df84749.gif)

**Comment by ramyaragupathy** [comment]
@Muskan284 - this is not front facing and it is a template file. Need not spend your effort here. Thank you!
