### ISSUE TITLE
Description texts for working groups

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#49]
We now have the possibility to present the working groups and assign people on the website to be members of them (#12). Before we can make this really public we'd need suitable and short (!!) texts for each working group: http://hotosm.org/working-groups

Thank you!

**Comment by xamanu** [comment]
For now I just took the ones from the wiki (not very good).

**Comment by russdeffner** [comment]
@xamanu is there no Security WG showing on http://hotosm.org/working-groups because no members?

**Comment by russdeffner** [comment]
Also looks like there is some inconsistent formatting with the member pics, I think it looks best in the Activation and Tech format.

**Comment by xamanu** [comment]
@russdeffner said in the last communication wg meeting, he would ask all groups to improve their text snippet in the wiki, so we can use these on: http://hotosm.org/working-groups

**Comment by russdeffner** [comment]
Sent message to membership which in theory catches all the wg leads; asked for them to also improve their wiki-page description as well; and inform us if they need help editing the website. I would say you could close this issue as the short text we have now works fine.

**Comment by xamanu** [comment]
Any news on that? Should we do further steps? Has there been some input that needs to be put on the website? Do we wait? Or just close it?

**Comment by russdeffner** [comment]
I think we can close it; soon we'll have solid wg leadership that can either edit themselves or know to reach us for help.

**Comment by xamanu** [comment]
Great! :)
