### ISSUE TITLE
handle country  selection  better

### ISSUE THREAD

**Issue by Muskan284** [hotosm/hotosm-website#492]
issues:-
1)there is a input type submit button with value go is present in code but not appearing in the get-involved page .
![Screenshot from 2019-03-22 13-55-23](https://user-images.githubusercontent.com/42279758/54824914-4a020400-4cd2-11e9-98e5-119ab00ec14a.png)
2)selection menu for countries seems to extend more
3)direction arrow has no use .i think it would be better if the hover effect is added
![Screenshot from 2019-03-22 13-55-10](https://user-images.githubusercontent.com/42279758/54824917-4b333100-4cd2-11e9-9796-3c9c97f6f42c.png)
@ramyaragupathy @smit1678 if these issues seems genuine .i would like to fix it.

**Comment by ramyaragupathy** [comment]
@Muskan284 - Thanks for taking the time to look through the website! This invisible submit button feature is per design. The button will work but will not be visible. The enter action works by default if the form's input is focused/used. 

Closing this and the related PR
