### ISSUE TITLE
Text out of box in update page

### ISSUE THREAD

**Issue by chauhannishh** [hotosm/hotosm-website#493]
![Screenshot from 2019-03-22 14-17-05](https://user-images.githubusercontent.com/34571079/54835893-0f579600-4ce9-11e9-946f-97a81c77649c.png)
@ramyaragupathy I would like to work on this issue. Should I go for it?
I am a Outreachy Aspirant.

**Comment by richa208** [comment]
Hi @chauhannishh !
This is not a bug but a designed pattern.
#448 was a similar issue and was clarified later by @ramyaragupathy.

**Comment by chauhannishh** [comment]
Okay. Thanks @richa208
