### ISSUE TITLE
Call to action text for activations

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#50]
We'd need a good and short text that gives people a starting point on how to get involved in activations. Check the dev site please:

http://www.dev.hotosm.org/activations (user and password is "hotosm")

**Comment by techlady** [comment]
Don't use the word "activations"! No one outside of HOT knows what it means!
What is needed is something very obvious on the Home page. My idea was big buttons, but I don't care as long as it's really visible.
How about "Nepal Earthquake Emergency Mapping"? 
And, yes, the buttons would change with each new activation.

**Comment by techlady** [comment]
You can put the same thing under "Get Involved."

**Comment by russdeffner** [comment]
My two-cents would be that we go with 'emergency mapping' and it actually goes under projects. We'd still need a sentence or two, such as "HOT is currently operating these emergency mapping projects. Click on a specific response to learn more and start contributing."

**Comment by techlady** [comment]
Russ,
I rather like "Crisis Mapping." It's shorter and has more punch.
As for what to say, how about just a headline saying "Current Crisis Mapping Projects"?

**Comment by xamanu** [comment]
Today in the communications working group it was proposed to use: Disaster Mapping. @techlady offered to write the text. Thanks!

**Comment by techlady** [comment]
As requested by Felix, here is a short text to explain "Emergency Mapping"
When a disaster or political crisis happens, HOT leaps into action to map the affected area. Disaster responders, such as the Red Cross and Doctors without Borders, tell HOT that having detailed maps, especially with roads and buildings, is a big help in responding to these crises. Anyone can get involved. To get started, go to the Tasking Master, which organizes emergency mapping.

**Comment by xamanu** [comment]
Thanks. Online: http://hotosm.org/emergency-mapping

**Comment by russdeffner** [comment]
@xamanu - there is no link to the Tasking Manager on the page.

**Comment by xamanu** [comment]
@russdeffner thanks for reporting. I just changed it. Btw, all content editors can do this as well.
