### ISSUE TITLE
Voting member view

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#51]
For the voting members it would be good to have a view of fotos instead a long list of names

**Comment by xamanu** [comment]
This is somehow related to #48.

**Comment by xamanu** [comment]
So, we have now a voting member list with photos: http://hotosm.org/leadership/voting-members
It is not linked from anywhere, so we can use this to make use we get all the data together.
Only members are shown, that are voting members (flag in the profile) and have a full name in the field in the profile. 

Maybe we should go through the accounts and compare it with the lists of voting members, adjust the full name, mark them as voting members and create new accounts for those who are not yet available.

It would be also good to invite all users to change their user picture and specify their country, but before we should have done #52 and #53.

**Comment by xamanu** [comment]
Practically #52 and #53 are on a level now, that we could invite people to complete their profile information and upload a picture.

**Comment by russdeffner** [comment]
As also commented in https://github.com/hotosm/hotosm-website/issues/52 There are 86 voting members, and this list is correct here: http://hotosm.org/our_board/membership
If the 'alumni' have profiles the should be deleted/archived

**Comment by russdeffner** [comment]
https://github.com/xamanu - once you have verified that all members can get to their profile, I will email the list; please provide 'very simple instructions' that I can give.

**Comment by xamanu** [comment]
Online: http://hotosm.org/voting-members
To go through all users and consolidate data is going to be handled in #60
