### ISSUE TITLE
User bar for authenticated users

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#52]
When a user is authenticated but has no editor nor admin role, there is almost no way to see that he/she is logged in, where to come to edit their own profile and how to log out.

The only thing that distinguishes a logged in from a logged out user is the small little link to logout at the end of the page. As we want the voting members to login, we have to give them a more intuitive way to find the stuff the can/should do on the website.

**Comment by xamanu** [comment]
Done. All users have now the grey toolbar on the top, when logged-in. When users have no role, they only have one link: My profile. This is a good start and can be extended, depending on more functionality we'd give to the users.

**Comment by techlady** [comment]
I'm not sure what is the purpose of this discussion. A relatively small number of people will have the ability to edit the web site: the executive director, Kristen, the board members, Felix (for example). Project coordinators will be able to edit only their own pages.

**Comment by xamanu** [comment]
We already have 93 user accounts on the website. Most of them can not do anything. Now people can at least find their own profile and we have the ability to add more to it, when/if needed

**Comment by russdeffner** [comment]
There are 86 voting members, and this list is correct here: http://hotosm.org/our_board/membership 
If the 'alumni' have profiles the should be deleted/archived
