### ISSUE TITLE
still video on project page not displayed in live website .

### ISSUE THREAD

**Issue by Muskan284** [hotosm/hotosm-website#520]
@ramyaragupathy @smit1678  the video is not showing in the live website. A pr related to this issue has already been merged.
https://www.hotosm.org/projects/haiti_
![Screenshot from 2019-03-31 12-56-52](https://user-images.githubusercontent.com/42279758/55286124-151e3d00-53b5-11e9-92c0-0ac9ca87a3a9.png)

**Comment by bismitaguha** [comment]
The changes commited are not being visible in the code.

**Comment by Muskan284** [comment]
@ramyaragupathy  please look into this issue
