### ISSUE TITLE
Updates/News images smaller than the width of the content box are resized to 100%

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/hotosm-website#529]
Example (bottom of page) https://www.hotosm.org/updates/cyclone-idai-how-can-you-help-by-mapping/ 

How it should work: 
Images that are bigger than the div width should be resized, but images that are smaller should be left alone.

**Comment by bismitaguha** [comment]
@dakotabenjamin can I work on this issue?

**Comment by smit1678** [comment]
Yes agreed, we don't want to allow images that are bigger than the width of the content container, plus for images that can be resized to 100%, we should encourage that so there is good symmetry on the page. Setting specific widths can always be done with the `<img>` and setting a width but this isn't straight forward for a new editor and is prone to errors given that you need to have the right format. 

Can we define a minimum width of an image that we leave alone?

**Comment by bismitaguha** [comment]
@smit1678 @dakotabenjamin we can set all images to be resized to a lower width by default. 
I would like to work on this issue Sir.

**Comment by smit1678** [comment]
@codefab99 Ok great, please go ahead. 👍
