### ISSUE TITLE
Theme user profiles

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#53]
User profiles don't look very good, especially the part of involved projects. This needs some theming love.
See, for example: 

* http://hotosm.org/users/jaakko_helleranta
* http://hotosm.org/users/mikel_maron
* http://hotosm.org/users/felix_delattre

**Comment by xamanu** [comment]
* Some progress here, but still more theming needed, in order to look really good.
* The twitter handle and the osm name should link to the external pages.
* Information about being a voting member, part of the board or the executive director (coming from flags) needs to be displayed on the profile.

**Comment by russdeffner** [comment]
I'm ok with mine: http://hotosm.org/users/russell_deffner

**Comment by xamanu** [comment]
Looks great! :) But I'd still like to improve it a bit: smaller headlines and a link to the Twitter and OSM profiles.

**Comment by xamanu** [comment]
Now I like it :+1:
