### ISSUE TITLE
Profile pics not showing

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#538]
It seems the pictures we took recently in Jakarta for the staff that had 'non-conforming' photos are not showing. Example - https://www.hotosm.org/people/russell-deffner/

**Comment by ramyaragupathy** [comment]
hey @russdeffner - seems like the [last commit](https://github.com/hotosm/hotosm-website/commit/1ebabd1327841231b3761ccfe7b264bbff8aa336) made for the 📷  updates does not include the new file uploads. Links have been updated in the related files, but the new files are yet to be uploaded to the system. As a temporary fix, I have reset the image links to old photo references. Let's wait for @smit1678 to upload the recent pics.
