### ISSUE TITLE
Remove stats fields for null data

### ISSUE THREAD

**Issue by bismitaguha** [hotosm/hotosm-website#540]
@ramyaragupathy the details are empty in country-page stats fields, but still a loading icon is visible. I feel we should remove the fields if null data is present. Please provide suggestions on this issue.
![Screenshot from 2019-04-17 13-37-08](https://user-images.githubusercontent.com/43119923/56271498-449faa00-6116-11e9-8f79-47c976c4d2f0.jpg)

**Comment by ramyaragupathy** [comment]
hey @codefab99 - there's already an issue related to this https://github.com/hotosm/hotosm-website/issues/363.
