### ISSUE TITLE
Allow users to select working groups and projects affiliation?

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#55]
We have some fields for the users:

* Projects they participated
* Working groups they are active

Right now, each user can define them by himself/herself. Is this the desired behaviour? Or do we want to restrict this to a certain role (content editor, or site admin)?

**Comment by russdeffner** [comment]
I think Projects and Working Groups is fine - self-selecting the "Board Role" we might want to restrict.

**Comment by xamanu** [comment]
Makes sense, @russdeffner. I implemented it like this. Only users (admins and editors) who are allowed to set board membership flags can not edit this field on the board role.
