### ISSUE TITLE
Press section

### ISSUE THREAD

**Issue by techlady** [hotosm/hotosm-website#56]
There should be a press page (section, actually) that includes
--Main page: basic info, including About HOT, press contacts, names of board and executive director plus links to subpages below
     --Press releases: a place to post all press releases, by date
     --Press resources: graphics, photos, video
     --HOT in the News: links to news articles about HOT or the articles themselves, by date

**Comment by xamanu** [comment]
Yeah, this would be great. Generally I see no technical problems on setting up such a section.
Before mixing it up with the content restructuring I would like to have it separate, so we can deploy one part and then do the other.

@techlady proposed to have it in the navigation on first level with the following sub-pages
.
* Press (with Press Contacts)
     * Press Releases
     * Updates
     * HOT in the News

Can we first start in the wiki to get the texts together for the general main page for this section?

**Comment by techlady** [comment]
Everyone,

A couple of more things that this part of the web site would need technically. These pages would be quite dynamic. "Press Releases," "Updates" and "HOT in the News" could be changed as often as daily. So, they need to be easy to post to. I also forgot to add a fourth subhead "Press Resources," which would include photos, logos, graphics (such as maps) and even video. Again, these pages need to easy to post to and could change daily.

**Comment by techlady** [comment]
As for the text, not much is needed. Much exists already. I will try to gather what there is.

**Comment by xamanu** [comment]
Yes, in order to build this, it would be good to have the text and the materials (logo, photos, graphics, videos...), so we can think about presenting them in a good way.

Yes, press releases and HOT in the news, would be special content types, which can be filled in with proper forms and are very nice and dynamical to handle.

**Comment by techlady** [comment]
Felix,
Each project is different, and for most of them we don't yet have copy or photos. What is needed is a page for each project that will be easy for the project coordinator to edit: to put in copy, to add photos, etc. 
Also, press releases are not really special copy types. Most press pages have a subpage labeled "Press Releases" with the date, headline and subhead of each press release. Each one links to a PDF of the press release. The press releases are usually in order by date with the most recent at the top. So, the page is a simple list with links to PDFs. 
As time goes by, the press releases for each year are gathered under a heading for each year (2014, 2013, etc.), which creates a kind of history of the organization.

**Comment by xamanu** [comment]
Thank you for the information @techlady! Hm, first I understood this as global (HOT) press section. Now I understand that it should be connected to each project. Do we have the wo/manpower to do this? Wouldn't it be just a good start to have a global section? And get the stuff together for HOT in general and then we see if we should extend it to the projects. Or is this feature request more towards having the ability to flexibly add "static" pages to projects?

**Comment by techlady** [comment]
No, Felix, I think you misunderstood me. The press page IS a global page. It is NOT connected to each project. The sentence I wrote above about the project pages is separate from the point I was making about the press page.

**Comment by techlady** [comment]
My idea for the project pages is that, as Russ suggested, each project should have its own landing page. Then, each project coordinator can add updates (text), photos, graphics, etc. Russ gave this page http://hotosm.org/projects/tanzania as an example.

**Comment by techlady** [comment]
Here is how I would structure the press page:
Press landing page (with press contacts)
--Press releases (list of headlines by date linking to PDFs of press releases)
--Press Resources (photos, etc.)
--HOT in the News

**Comment by xamanu** [comment]
Please get all stuff together on a wiki page and then we can check how to technical implement this. Thank you!

**Comment by xamanu** [comment]
This seems to be dead. I'm closing this for now. Please re-open when it becomes relevant again.
