### ISSUE TITLE
Country page: Fix tooltip content in the stats section

### ISSUE THREAD

**Issue by katia-utochkina** [hotosm/hotosm-website#563]
Content inside the tooltip in the stats section needs to be modified. At the moment, it contains a technical term - API  - which for most users is unfamiliar. The term should be avoided to improve readability.

![api11](https://user-images.githubusercontent.com/16920088/59085051-00ef4280-8906-11e9-8bf1-df391f551c10.jpg)

**Comment by BrunoM24** [comment]
Hey, I can do this
