### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#57]
Do we want the mail form (http://hotosm.org/contact ) on the website to be linked in the main navigation? Or maybe in the footer? @techlady mentioned it in the restructuring content process (#15) and it is indeed not linked anywhere.

I'd also suggest we need a (very) brief text to introduce the contact form. What do you think?

**Comment by xamanu** [comment]
Ah, and the email addresses in the website are not good, as they do not reach HOT. Before we get this out, we need proper email address(es): #44

**Comment by techlady** [comment]
Felix,
What do you see as the purpose of this email contact form? Is it just to contact someone at HOT? And, where would it be? On the "Contact" page? We also need to have phone numbers.
Also, I'm not sure what you mean by "linked in the main navigation" or "Maybe in the footer,":

**Comment by mikelmaron** [comment]
info@hotosm.org is the main catchall. * Mikel Maron * +14152835207 @mikel s:mikelmaron 


     On Monday, May 11, 2015 10:53 AM, Charlotte Wolter <notifications@github.com> wrote:
   
 

 Felix,
What do you see as the purpose of this email contact form? Is it just to contact someone at HOT? And, where would it be? On the "Contact" page? We also need to have phone numbers.
Also, I'm not sure what you mean by "linked in the main navigation" or "Maybe in the footer,":—

**Comment by xamanu** [comment]
@techlady, I thought you mentioned it. For me there is no need to put this anywhere, as the email is publicly available. So, closing here. Thank you!
