### ISSUE TITLE
Improve the "Updates" page visually

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#58]
That page is just sort of a list of small excerpts from the updates, it would be nice if it could just get improved a little, maybe pull in some graphics from the updates as well?

I don't have a good idea for how to make it look better honestly, but if Felix could give it a try I am sure it will improve.

**Comment by xamanu** [comment]
@bgirardot Here are some tweaks to the updates page: http://www.dev.hotosm.org/updates (username and password is "hotosm").

What do you think? It is not a huge improvement, but added some more space between the entries and showing the first image of each article (if there is one)

**Comment by xamanu** [comment]
Done: http://hotosm.org/updates
