### ISSUE TITLE
Staff view

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#59]
@mataharimhairi mentioned today, that a staff view is requested. In order to be able to develop something like that, I'd like to know, what staff HOT is having right now.

* Executive Director
* Technical project manager

....???

**Comment by xamanu** [comment]
@KristenEgermeier said in email conversation that the positions for staff in HOT would "change fairly frequently", so we should think about a simple checkbox for users, when they are a staff member and a free textfield for their position.

**Comment by xamanu** [comment]
I started adding two fields to the users:

- [x] A flag to select a user as a "staff member"
- [x] A text field to specify the "staff position"

Next steps are:

- [ ] A view to display and order staff members
- [ ] Identify all staff members and their positions. This could be a list that is sent to me, or it can be edited by admins on the website directly.

**Comment by mataharimhairi** [comment]
@xamanu I e-mailed over the list of current staff members with their positions. I guess you can initially add them, and they can be adjusted individually as things change, if that works for you?

**Comment by mataharimhairi** [comment]
@xamanu I tried out the staff page and it is looking really good! I love that you can link the projects we are working on. However there are only links to projects currently listed under the Projects page. 

Other projects such as developing the Field Papers tools, the Activation Curriculum and OpenAerialMap would have to be added, but I assume you need the information. Should I go ahead and add these as separate issues?

**Comment by xamanu** [comment]
@mataharimhairi yes, this is fine. I add the users and they can later specify their data.
Which staff page have you been looking at?

Al things regarding the project pages should be a new issue or, in case it is connected, to be posted in #21.

**Comment by russdeffner** [comment]
@xamanu @mataharimhairi this is somewhat related with https://github.com/hotosm/hotosm-website/issues/60 and https://github.com/hotosm/hotosm-website/issues/62 - I think for now it is easiest if we can 'lump' everyone (staff, voting members, etc.) into "Leadership", example why is currently my profile: http://hotosm.org/users/russell_deffner is showing "Board Function: Chair of Voting Members" which isn't technically a 'board function'

**Comment by xamanu** [comment]
@russdeffner I don't think it would be a good idea to put everyone into Leadership. It makes sense, technically to handle separately being staff, a voting member or part of the board.

I agree that Chair of Voting Members should not be in the Board function, as you are not on the board. And we should figure out in #62 how to handle this very special case.

**Comment by xamanu** [comment]
In #62 @russdeffner proposed to make a separation on the users between:

* staff
* contractors

Do we have to display them separately? Or wasn't it just a naming issue that we wanted to call the whole section "Staff and contractors"?

**Comment by KristenEgermeier** [comment]
They need to be named separately as well. 
Thanks,
Kristen


Kristen Egermeier
Operations Manager 
805-279-1116

**Comment by xamanu** [comment]
ok. Good to know. Will we have more types of staff in the future? Would volunteer leads fit under staff, as separated as staff, contractors, volunteer leads?

**Comment by KristenEgermeier** [comment]
In the future we might want to include those, but not under staff. 


Kristen Egermeier
Operations Manager 
805-279-1116

**Comment by russdeffner** [comment]
Something that @xamanu and I discussed about this (please correct me Felix).
Basically at the 'highest order' of 'flags' (i.e. categories of users) we currently have: "voting member", "board member", "staff" and "executive director". 

I think we need this to be: "voting member", "board member", "staff and contractors" and "(other)Leadership". The (other) Leadership would be for our volunteer leads who don't fit any other role, but may lead a technical project or activation, etc. and therefore should have a profile to link/post from.

**Comment by mataharimhairi** [comment]
@russdeffner @xamanu How about this:

* Voting Member
* Board Member
* Executive Director
* Staff
* Interns
* Leadership (other) - to include volunteers such as the mentors on the Outreachy program and the great work by Pierre Beland, Rafael and Maning, just to name a few.

**Comment by xamanu** [comment]
ok! I think it becomes clear we want to have for sure:

* Voting Member
* Board Member
* Staff
* Leadership (other)

But there are other categories that are mentioned and I'd suggest to put them in a second level hierarchy under staff:

* Executive Director
* Employee
* Contractors
* Interns

There could be a drop-down selection "staff type", similar to what we have already for the "board role".
Please note, we are talking about the selection in the profile and hierarchy of classification. This does not imply how we present staff on the website. So, e.g. it would be still possible to show the ED on the board view (if desired). Or we could show, let's say interns, separately from anything else.

**Comment by mataharimhairi** [comment]
@xamanu this sounds like a good layout to me!

**Comment by xamanu** [comment]
ok. I this can now be select on user profiles. I also started to implement a basic staff view: http://hotosm.org/staff (this is not visible to anonymous users). We can now proceed to create user profiles for the HOT staff and assign the right flags and information to them.

**Comment by russdeffner** [comment]
The communications wg discussed and agreed that this shouldn't be called the "Staff" page - if so, we should not include contractors, interns, etc.  Our alternative suggestion is to call the page either "Leadership" or "Team" and include all staff, contractors, interns and volunteer leads. (also updated the content wiki to reflect)

**Comment by russdeffner** [comment]
Another title I thought for this that might work/be more 'neutral' is 'operations' or similar.

**Comment by TylerRadford** [comment]
We already have the Board page. I suggest we change the menu link to "Leadership" since it includes two subheadings: 1) Our board and 2) Executive Director (see screenshot)

We can create a new page "Team" (the "Team" language is commonly used across a large percentage of websites).
On that page we can have three subheadings:
1) Staff/contractors

2) Volunteer leads

3) Interns

![leadership](https://cloud.githubusercontent.com/assets/9853903/8387598/dc7ba49c-1c27-11e5-8afd-59e3bd4e4a32.JPG)

**Comment by xamanu** [comment]
It's online now, implemented during the redesign work.
