### ISSUE TITLE
Unify domains

### ISSUE THREAD

**Issue by dodobas** [hotosm/hotosm-website#6]
For example pages http://hotosm.org/get-involved and http://www.hotosm.org/get-involved show different content. I guess that the page *www.hotosm.org* is somehow outdated, maybe there is a cache problem...

**Comment by bgirardot** [comment]
For what it is worth, I see that

http://www.hotosm.org/
and
http://hot.openstreetmap.org/

Are out of sync at the moment.

The page cache notice on www.hotosm.org seems to be quite old:

**Comment by harry-wood** [comment]
> the question which name, is more a policy decision than a technical one

It's kind of a policy decision although there's tech aspects to it.

I don't think we can redirect tasks.hotosm.org to tasks.hot.openstreetmap.org (and not sure if we would want to)   But leaving tasks.hotosm.org where it is, while having our website at hot.openstreetmap.org is arguably less tidy. There's a certain clumsiness about having tasks.hotosm.org but then if you delete the 'tasks' from the URL, getting redirected (However this redirect *should happen* if we are deciding this. We need to decide and redirect one way or the other)

And likewise we have the same problem with http://export.hotosm.org  . Not sure if there's any other subdomains we've set up.

So yeah those are some semi-technical reasons why our website might be better at hotosm.org (and redirected off hot.openstreetmap.org )  I think that would be my recommendation.  And I say that as somebody who has been tending to point people at  hot.openstreetmap.org  :-/

**Comment by xamanu** [comment]
This makes sense to me @harry-wood (being one who also points people to the hot.openstreetmap.org domain).

I think it would be good to come to an decision here, as caching problems occur and those are partly related with the different domains, we are serving the site.

**Comment by IknowJoseph** [comment]
Not only do we have issues of websites on subdomains, such as summit.hotosm.org, but we also have email addresses such as summit@hotosm.org (not to mention all of us who have our.name@hotosm,org).

I would say we standardise on hotosm.org and have hot.openstreetmaporg redirected to there.

**Comment by xamanu** [comment]
Thanks for all the different opinions. This all seems very reasonable. How is the process on decision making? We could take a final decision in the next TechWG meeting or is this something the board should review?

**Comment by harry-wood** [comment]
Actually I think the tech justification is strong enough that this should just be made to happen. We can do this on our own servers using a .htaccess file right? Maybe we could do a "302 (Temporary) Redirect", so that this decision can be reversed if necessary.

**Comment by IknowJoseph** [comment]
Sounds good @harry-wood 

Could this also be done with the sites-enabled entry? That's where I'd go to first, but I suppose it's personal preference(?)

**Comment by dodobas** [comment]
Done ... everything now points to http://hotosm.org ... for example http://hot.osm.org/projects/

**Comment by xamanu** [comment]
Thank you @dodobas!
This here can be closed, I will have a look on #39 as this need some more verification.
