### ISSUE TITLE
Consolidate user database

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#60]
For the staff view (#59) and the voting member overview (#51) we need to make sure that we have solid data about users in the system.

Right now we have:

* 98 user accounts on the website

We have to make sure:

* All 83 voting members have an account, and are marked as voting members on their profile.
* All staff members have an account, and are marked as staff on their profile.
* Check on the other profiles, why these are there (volunteers, e.g.), or should they be removed/blocked?

**Comment by russdeffner** [comment]
Also commented on https://github.com/hotosm/hotosm-website/issues/51 - there should be 86 voting members, list at http://hotosm.org/our_board/membership is correct

**Comment by xamanu** [comment]
@russdeffner wrote in #43: "I will write an email to the membership after the meetings today - asking for everyone to update their profiles, as well as some of the other issue needs."

This is great! Please ask voting members that have no profile to create one: http://hotosm.org/user/register

I'd like to give it a 48 hours timespan. Of course, I know, not everybody will make it. But this allows us to keep registration open for just some time and hopefully most of the people to check their profile soon.

**Comment by xamanu** [comment]
@russdeffner I can give you a short text you can use in your email. Give me a couple of hours to wrap some functionality up and I send it to you.

**Comment by xamanu** [comment]
@russdeffner I propose another workflow:

1. Through the website I send out an email to all existing accounts, asking them to update their profile.
2. After 48 hours we compare the list of voting members to a new user view I just created (only visible for admins) http://hotosm.org/admin/hot-users
3. We compare the list of staff members to the new user administration view.
4. We create new accounts when needed
5. We get a list of unknown users (not a voting member, nor staff) and check those manually if we want to keep these or delete them.

**Comment by russdeffner** [comment]
Yes, absolutely - as I assume you, @xamanu already compared with the member spreadsheet I shared with you?

**Comment by xamanu** [comment]
Yes, on the website we have 68 accounts marked as voting-members. On the list we have 86. There is a difference of 18. I'd like to have people updating their full name, so we can match them more easily and detect the ones that are not marked as voting members or do not have an account.

**Comment by russdeffner** [comment]
ok, so this is maybe related to the issue I just created: https://github.com/hotosm/hotosm-website/issues/62 - before we send invite, we should probably just go ahead and let everyone set their 'leadership role', maybe some of the other accounts just aren't set as voting members yet; also then staff can select staff or contractor role (is that implemented? should I open issue to add those two to the drop down list currently known as 'board function'?)?

**Comment by xamanu** [comment]
Mail sent out to all users. Waiting now two days (at least) for people to update their profile.

**Comment by xamanu** [comment]
@russdeffner and I have been sending out emails to the members. There are still 48 accounts which have not been updated since then. I sent a reminder email to them.

**Comment by russdeffner** [comment]
@xamanu ok - I also sent a message to the membership this weekend, of course lots are in disconnected environments, so it may take weeks for them to actually see the emails and respond. Looks like we have about 1/2 of the members on there with at least some minimal information in their profiles, so I think we are doing good.

**Comment by russdeffner** [comment]
@xamanu - as discussed on Mumble; we should make the Country optional, and if it isn't there already; allow for those who already selected to pick 'blank' - I think several people 'randomly' put a country that isn't correct but if they prefer not to show country, not sure they have a way to 'deselect'

**Comment by xamanu** [comment]
* Country is optional
* People can select "-None-" to deselect their country

**Comment by russdeffner** [comment]
Ok, I went through the profiles again and all of the 'never accessed' accounts are voting members; the ones that I could identify as duplicates (i.e. they also have an account they are actively using) I deleted. The only tricky one is John Crowley who has two active accounts (i.e. he has created content with both - I think); so I will leave that one up to the experts for how to merge.

**Comment by russdeffner** [comment]
I also reviewed all the Profiles for voting membership - or more specifically I compared my official list of members (names or emails) to the user list on the website.  By my count 70 of the 86 members have a profile and I went ahead and entered their names so they all show up on the voting member page now: http://hotosm.org/voting-members - I think a little more wait to try and get more pictures/profile details from existing profiles before creating the missing 16.

**Comment by russdeffner** [comment]
@xamanu - all voting members now have a profile on the website, new ones were emailed individually to log-in with our 'usual' temporary password and update, etc.

**Comment by russdeffner** [comment]
@xamanu - ok, I have now gone back through the entire user database and done my best to delete the duplicate accounts (I think all are handled except John Crowley's two that are both in use).  I also marked all the Staff as appropriately as I know and can say that comparing with the Project Org Chart that Tyler made, only Brian O'Hare, Paul Uithol, Adityo Dwijananto and Lia Indriati are the only ones without profiles (minus interns) - probably Paul is the only 'real important'/i.e. manager level person without.

**Comment by xamanu** [comment]
@russdeffner, thank you so much for this work!! This is really great. And it motivates to see comments like the one of @harry-wood  in the email: "We can see each other!" :)

I'm closing this here now. Staff user profiles we can handle in the issue for staff.
