### ISSUE TITLE
Special leadership roles

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#62]
This is mainly a suggestion to switch "Board Function" section of user profiles to "Leadership Role" as technically the Chair of Voting Members is not a 'Board' thing; this would also allow things like Staff and Voting Members to more accurately be included there.

**Comment by xamanu** [comment]
I agree, Chair of Voting Members should not be inside Board functions. The executive director is right now a special "flag", which does not seem to fit either. So let's use this issue to talk about these.

Do we need a separate category for leadership roles? Are the more than Chair of Voting Members?
Executive director should go under staff, I guess...?!

As this is just related to a few people it is not necessary to wait with asking people to login and complete their profile (#60)

**Comment by russdeffner** [comment]
I think this simplest answer right now would be to simply change the title of that section on the user profile to "Leadership Role"; then we can have a list; here is my best attempt:
* Board Member
* Voting Member
* Staff
* Contractor
* Volunteer Lead

I think that makes it general enough for the meantime, then during longer overhaul we can figure out if we need more/less/special 'flags'

**Comment by xamanu** [comment]
Yes, volunteer lead sounds great!

**Comment by xamanu** [comment]
I introduced on the website now a flag for "Volunteer leads" and a free textfield to fill in their role. Right now those are shown on the staff view http://hotosm.org/staff (you must be logged in). Or what would be the appropriate place for volunteer leads to be presented?

**Comment by xamanu** [comment]
I introduced on the website now a flag for "Volunteer leads" and a free textfield to fill in their role. Right now those are shown on the staff view http://hotosm.org/staff (you must be logged in). Or what would be the appropriate place for volunteer leads to be presented?

**Comment by russdeffner** [comment]
I was thinking we might also recognize volunteer leads such as yourself @xamanu - i.e. if we create a project page for LearnOSM and Althio volunteers to be lead/contact, then he would also be a good candidate for a profile with 'volunteer lead' flag.

**Comment by xamanu** [comment]
ok. But where do we want the volunteer leads to show up? On a special page or together with staff?

**Comment by russdeffner** [comment]
I'll add this to discuss with Tyler, he may need to run it by the Board.

**Comment by xamanu** [comment]
It's online now. Closing here.
