### ISSUE TITLE
Adding additional HOT activities and projects

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/hotosm-website#63]
I would like to add some additional projects that are not country or activation specific, but are also important as the public should be informed on other activities of development HOT are involved with. This allows them not only to be informed but also provide them the contact details if they also want to contribute or collaborate:

* Field Papers Development
* Export Tool Development
* Activation Curriculum Development
* The Outreachy Program 

Just wanted to bring this up and get it started. If its fine to go ahead with its creation, I will provide the rest of the required details!

**Comment by xamanu** [comment]
I'd say yes @mataharimhairi. Especially after introducing the categories for projects we now can add other types of projects. You can add projects by clicking "Add project" on the top navigation bar for "content editors".

**Comment by russdeffner** [comment]
@mataharimhairi and @xamanu - correct me if I am wrong, but are we not 'waiting' on some of these Tech projects to get a Project Page built before we 'launch' the categorizing? In other words - can I help by building some of these pages? I also sent a note to @dodobas that we would be doing this soon so maybe he can help get text and graphics for LearnOSM, the TM, etc. from the volunteer leads of those projects.

**Comment by xamanu** [comment]
@russdeffner great, please go for it!

**Comment by mataharimhairi** [comment]
@russdeffner you are correct, we are not waiting for the categorising before the project pages can be created. I just personally haven't had the time to start any of them yet. So please go ahead and start building them, and then I can fill out the details of the projects mentioned above that I am managing.

**Comment by mataharimhairi** [comment]
@russdeffner actually I got excited and starting making the pages for the following:

* Field Papers Development
* Export Tool Development
* The Outreachy Program

I have left the Activation Curriculum to your devices though!

**Comment by xamanu** [comment]
Dear @mataharimhairi, this is great. Unfortunately I could not find the projects on the website. Please post them on the website when ready. Thank you :)

**Comment by russdeffner** [comment]
Ok, I added the Activation Curriculum Project Page - using a slide for the image currently and of course it doesn't fit the square, so I'll fix that in the near future or find a better image.

**Comment by xamanu** [comment]
What about the old activations? Do we want to have a complete list on the website or just the ones, that make it there? http://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team#The_OSM_Tasking_Manager

And I see the Missing Maps project missing. There should be more.... aren't there?

**Comment by russdeffner** [comment]
I think we are ok not to go back and add all the mapping projects listed on the wiki.

As far as Missing Maps, I think we do want 'separation' from projects specifically launched via HOT.  I do think that maybe a page/project for Missing Maps that just gives a brief and link to their website would be good though.

**Comment by mataharimhairi** [comment]
The project pages are up! Perhaps an 'Events' section under the Projects page could work? Missing Maps is more or less mapping parties to fill in absent data. The most important thing for us to display is where and when the next Missing Map event is for people who want to start contributing.

**Comment by russdeffner** [comment]
@mataharimhairi - I think though, that M.M. projects are so frequent, etc. that it doesn't fit our main website very well.  It seems that even on their main page often the events are not 'archived'/updated very frequently (as of writing this they still have one up for 22 May); so asking to keep events up-to-date on both sites may be asking too much.

**Comment by mataharimhairi** [comment]
@russdeffner We could at least link through to their site from ours so that people can get the updates on events there. As you are right about us having to continuously update and that it very may well slip through the cracks.

**Comment by russdeffner** [comment]
Just noting that the communications wg identified to missing projects: the TM and LearnOSM - need to build project pages

**Comment by russdeffner** [comment]
Added quick project page for LearnOSM - will inform the coordination mailing list/ask for review contacts, etc.

**Comment by russdeffner** [comment]
I am working on a page for the Tasking Manager now, should have it up in a few hours.  @xamanu - I think we can effectively call this issue resolved; there may be other projects we should add, but all the 'major' ones are done.

**Comment by xamanu** [comment]
Thank you very much for nourishing the website!! This now looks way better and we represent more diverse work which is done in HOT.
