### ISSUE TITLE
Update Guidestar logo in Footer

### ISSUE THREAD

**Issue by vannicer** [hotosm/hotosm-website#633]
Sorry, tried to find location in siteleaf to edit myself but we need to edit the footer to be the new Guidestar logo for 2018 (2019 soon) 
Logo attached
![Guidestar Gold 2018](https://user-images.githubusercontent.com/24594890/72930295-9faba080-3d29-11ea-8439-e58956779c84.png)

**Comment by vannicer** [comment]
2019 Gold good for site- 
![Guidestar Gold 2019](https://user-images.githubusercontent.com/24594890/72931640-3f6a2e00-3d2c-11ea-83f5-99493cb24c47.png)

**Comment by ramyaragupathy** [comment]
![image](https://user-images.githubusercontent.com/12103383/72997304-2c398a00-3e22-11ea-92ec-55431a13982b.png)
