### ISSUE TITLE
OSM.ORG map should link directly to where to report tile problems

### ISSUE THREAD

**Issue by jidanni** [hotosm/hotosm-website#638]
Let's say a user is browsing say
https://www.openstreetmap.org/#map=11/29.0277/114.9596&layers=H
and sees
![32593-0](https://user-images.githubusercontent.com/1230959/74678385-cd371d00-51f5-11ea-8092-18fe8b925d12.jpg)
some forest tile abruptly cut off.

Well, he notices the "Tiles style by ..." and clicks it,
taking him to https://www.hotosm.org/ and still millions of miles from wherever he is supposed to file a bug.

**Comment by willemarcel** [comment]
@jidanni The goal of the attribution is to give credits to the authors of data and map style. The osm.org website has other tools to report problems.

**Comment by jidanni** [comment]
> The osm.org website has other tools to report problems.

Yes perhaps, but not on this page.
