### ISSUE TITLE
Backup strategy

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#64]
As far as I know we are not really backing up anything. Code is in github, which should be fine. But the database should be regularly exported and saved in some place. @dodobas is there such a backup server where we can upload database backups?

I'd be happy to write a small script that does this on a regular basis.

**Comment by dodobas** [comment]
we have daily database backups, which run early in the morning (UTC), backups are kept for last 365 days (at the moment) and copied to the external server

**Comment by xamanu** [comment]
ok great! thanks. closing here.
