### ISSUE TITLE
Testimonials of partnerships

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#65]
There has been risen the idea of having a testimonials section, where representatives from NGOs and partners (MSF, Redcross, etc.) can write a testimonial to show on the web site. They don't just have to say nice things about us. They can also provide information about how we work with them productively.

This would definitely give credibility to the project, especially for potential contributors who are not familiar with the OSM world.

**Comment by russdeffner** [comment]
Actually maybe this should be part of #56?

**Comment by xamanu** [comment]
For me it has nothing to do with the press page. It is more related to HOT being a bridge between the OSM community and classical organizations. It would give HOT credibility in a nice way, as these quotes can be presented nicely and show that HOT is connected to well-known organizations.

**Comment by russdeffner** [comment]
Ah, so then I would say this is more 'partnerships' than testimonials.

**Comment by KatjaUlbert** [comment]
In my opinion testimonials are part of the community section, in our case that would be "get involved". I think one or more testimonials should be presented on the homepage with a short text plus a picture (close-up, postive charisma), text and picture equivalent in size. it´s a very useful and easy-to-make tool to create credibility and community feeling. They should be changed every few month to ensure all kind of target audience is represented (gender, age, country, educational background). I am not sure there´s a need for an extra testimonials page, they could be part of emergency mapping. this would also be a nice reference to the homepage (meet HOT>>>get started in just one click)

**Comment by KatjaUlbert** [comment]
any plans to present  "ordinary" testimonials, people who began mapping due to a HOT activation?

**Comment by KatjaUlbert** [comment]
In my opinion these testimonials (not collaborators) are part of the community section, in our case that would be "get involved". I think they (1-3, depending on the layout) should be presented on the homepage with a short text plus a picture (close-up, postive charisma), text and picture equivalent in size. it´s a very useful and easy-to-make tool to create credibility and community feeling. They should be changed every few month to ensure all kind of target audience is represented (gender, age, ethnic group, educational background). I am not sure there´s a need for an extra testimonials page, they could be part of emergency mapping. this would also be a nice reference to the homepage (meet HOT>>>get started in just one click)

**Comment by xamanu** [comment]
Yes, @russdeffner, Partnerships or Outcomes would be better words for this section.

@KatjaUlbert what you are describing would be indeed more a community feature, to represent different people. But the principal idea of this issue is more to underline the *seriousness* of HOT, as the organization is working with great partners all over the world, and this is not getting documented in a good way, that would give HOT credibility. It should be a page, where everybody sees: Wow, this has HOT achieved and with this famous organizations.... something like that :)

**Comment by grinapo** [comment]
I originally wrote an email in a very similar topic to @xamanu. 

There are some highly critical voices suggesting that HOT (and mapping for foreign lands in general) is a fancy Western White Man Thingie™ and that all of these works are uncalled for and in the reality unused by the people living/working/rescuing there. Some suggests that the armchair mapped maps are useless for the local people; some suggests that premapped areas are stopping locals from surveying their own environment, others suggest that the cited organisations barely utilise the results of the efforts.

Others just wondering where their dozens of hours of work really goes and they want to be sure that it is not wasted on some idealistic theory. ("Look, these guys Bob and Will used MY tracks to save these girls from whatever! There, that road in the back left, that was drawn by me!" :))

Real life examples, specifics, description of where it actually helped and how. Stories of the locals whether they like it or not, whether they would like to these things differently, what they're very happy about, etc. We have plenty of great (news and other) articles describing what have been done but articles about actual use and effect are hard to find. (Lots of articles mention organisations, vague claims about usefullness but it's really rare to see specifics.)

**Comment by xamanu** [comment]
In #84 a more lightweight approach to this is proposed. Instead of testimonials we could just call it "showcases" where we post about good uses (good maps, good collaborations, good partnerships) lead to real life results. It seems to me, that the basic request is very much related.

**Comment by grinapo** [comment]
My original point is, however, not about the availability of OSM based HOT maps but their actual and practical use by external people, preferably their _intended_ audience. There are plenty of showcases around, I could look up a few if anyone fancy that (for example the Google+ osm group have one for about every week), but I have seen close to nil about their real use.

**Comment by xamanu** [comment]
We are now collecting examples here: https://docs.google.com/document/d/1XwNa2Sr0zS3hEzxBmrWaHLDOcWXR0dgfMaPOCVOZ6Jw/edit
Please help out!

**Comment by KatjaUlbert** [comment]
@xamanu I guess we implemented this on our new partner page?

**Comment by xamanu** [comment]
@KatjaUlbert: No, this is not there. We have to see where we can put this in.

**Comment by xamanu** [comment]
Closing as duplicate. Please continue discussion here: #84.
