### ISSUE TITLE
Local communities section

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#66]
Quite some times there has been the vague idea to represent local hot communities. To me it is not very clear how this should look like. But let's discuss this.

**Comment by russdeffner** [comment]
Hmm... this is a tricky one; on one hand it sounds great. The other, we'd have to be very careful in 'selecting' those communities because if they are more general OSM communities, then we probably do not want to be perceived as selectively supporting some versus others and then there has been many ideas to make more community/social enhancements to the main OSM website - so we also don't want to 'step on toes'.

**Comment by xamanu** [comment]
Good point! I posted it here, because it was mentioned before. But I never understood which are local communities in relation to HOT. Maybe we can ask the board and the communities working group for input, and maybe this is really just not a good idea to do (at least right now).

**Comment by KatjaUlbert** [comment]
I also think it´s nice to have  but not that urgent. I met both the Berlin OSM and Missing Maps communities, some of them are HOT contributors as part of their OSM activities. But maybe there are OSM communities that emerged due to a HOT activation.

**Comment by xamanu** [comment]
I put it as "postponed" so we do not loose it, but it is not something we are going to tackle now.

**Comment by xamanu** [comment]
@KatjaUlbert mentioned in another issue (#65) a good idea to the community section: People's testimonials

> In my opinion testimonials are part of the community section, in our case that would be "get involved". I think they (1-3, depending on the layout) should be presented on the homepage with a short text plus a picture (close-up, postive charisma), text and picture equivalent in size. it´s a very useful and easy-to-make tool to create credibility and community feeling. They should be changed every few month to ensure all kind of target audience is represented (gender, age, ethnic group, educational background). I am not sure there´s a need for an extra testimonials page, they could be part of emergency mapping. this would also be a nice reference to the homepage (meet HOT>>>get started in just one click)

**Comment by KatjaUlbert** [comment]
Is this still urgent?

**Comment by xamanu** [comment]
I don't see anybody comming up with relevant proposals or ideas. So I will close it for now. Once the community working group has more clear ideas we can discuss them.
