### ISSUE TITLE
Undefined value in year filter on country pages

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/hotosm-website#668]
**Actual Behaviour**

On country pages after initial page load campaign filters populates year filter with undefined value
![image](https://user-images.githubusercontent.com/12103383/84895890-a7952400-b0c0-11ea-9aaf-4c1f1d55cb55.png)

**Expected Behaviour**

Either show just the years or attach the number of projects to each year.

![image](https://user-images.githubusercontent.com/12103383/84895702-59802080-b0c0-11ea-87d6-319a1598c983.png)

**Comment by max-keviv** [comment]
@ramyaragupathy  can you give the link for country page
