### ISSUE TITLE
Project Category (EM, CB, Tech) Pages - Change "Archive" to 'something better'

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#67]
The communications wg suggested a change to the 'sub-category' title of "Archive".  Some suggestions for alternatives were: "Past Projects", "Complete Projects" or "Successful Projects" - and some variations, a few I didn't catch, etc...

**Comment by russdeffner** [comment]
Having thought about this more, since it is "Ongoing", maybe just simply "Complete" instead of archive would do?

**Comment by xamanu** [comment]
I agree. Done. Changed to "complete"
