### ISSUE TITLE
Improve "Tools & data" page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/hotosm-website#672]
We have a list of "Tools we use:" on https://www.hotosm.org/tools-and-data and each tool linked directly to an external website, it would be better to:
- Link to the section of that page where we mention it
- Present each tool with a brief description and a link to both website and repository

**Comment by max-keviv** [comment]
@willemarcel  can i work on this

**Comment by willemarcel** [comment]
@max-keviv sure, you can do it

**Comment by max-keviv** [comment]
@willemarcel  can you give file link associated with  https://www.hotosm.org/tools-and-data 
it would be help, As i can't find file

**Comment by willemarcel** [comment]
Style: https://github.com/hotosm/hotosm-website/blob/gh-pages/_layouts/tools-and-data.html
Content: https://github.com/hotosm/hotosm-website/blob/gh-pages/tools-and-data.markdown

**Comment by max-keviv** [comment]
@willemarcel  I am facing problem in running website locally after downloading the repository.through documentation i couldn't figure out how to run
it would be kind of you. if you could help me to figure out how to run it locally 
thanks for your help
