### ISSUE TITLE
Project Category (EM,CB,Tech) Pages - Further Delineate Current/Past

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#68]
A bit related to #67 - please make the delineation of the ongoing projects and archive/past projects sections a bit more obvious.  A few suggestions from the communication wg: a line across the page between the sections and/or making the image/icons of the past projects smaller than current ones.

**Comment by xamanu** [comment]
Note to myself: When touching the theme, this can be done together with the other "urgent" theming issue: #73

**Comment by KatjaUlbert** [comment]
@russdeffner Problem is solved in the redesign. Close issue?

**Comment by russdeffner** [comment]
Thank you, covered in redesign.
