### ISSUE TITLE
Job postings not closing automatically on website

### ISSUE THREAD

**Issue by danagallaty** [hotosm/hotosm-website#696]
**Actual Behaviour**

Job postings on hotosm.org/jobs/ are not automatically moving to 'recently closed jobs' after the deadline has passed.

**Expected Behaviour**

Once the posting's deadline has passed, the job should automatically move to 'recently closed jobs'.

**Steps to reproduce it**

**Screenshots of the issue**
<img width="1250" alt="Screen Shot 2020-08-04 at 2 17 20 PM" src="https://user-images.githubusercontent.com/67422909/89287930-79ae7380-d65d-11ea-867a-e33e26bc719d.png">

**Would you like to work on the issue?**

I need someone else to address the issue.

**Comment by willemarcel** [comment]
As we switched to BambooHR, I believe we can close it.
