### ISSUE TITLE
Project Page Layout - utilize the right-hand side more

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#70]
There are a few things we suggest moving/adding to the right hand side of the individual project pages:
* Move the "Timespan" to upper right (i.e. above Project Page/Contacts)
* Move Project Type to right hand (lower/maybe last and/or even below picture)
* Add Member/member pic (tiny - i.e. such as working group page) to the right-hand side

**Comment by xamanu** [comment]
This is something which implies more technical work, therefore I would like to leave this is a comment to the happening redesign (#23). Instead of changing it now and in some nearer future again.

**Comment by KatjaUlbert** [comment]
the website has been redesigned, so I think we can close this issue.

**Comment by russdeffner** [comment]
Covered in redesign.
