### ISSUE TITLE
Error on Donation page for mail-in donations

### ISSUE THREAD

**Issue by danagallaty** [hotosm/hotosm-website#703]
**Actual Behaviour**

If you click on the link on this page: https://www.hotosm.org/donate/ in the phrase "To donate via mailing a check, please use the paper form", it shows "404: page not found"

**Expected Behaviour**

That link should bring the person to this donation form for mailed in checks.
[Donation Form- Mailing.pdf](https://github.com/hotosm/hotosm-website/files/5056755/Donation.Form-.Mailing.pdf)

**Would you like to work on the issue?**

I need someone else to work on the issue.

**Comment by wireguy** [comment]
fixed by #712
