### ISSUE TITLE
Font/Size Continuity

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#73]
There was a general suggestion from the communication working group to revisit the various text sizes used throughout the website - example: on the Projects page if the text of the project name was smaller, maybe most/all could fit on one-line (in most desktop browsers). Also we think the 'high-level-site-nav-bar' (i.e. about, updates, projects...) could be bigger and to a lesser extent the sub-menus(grey bar).

**Comment by russdeffner** [comment]
Also, my latest Mongolia blog post I think I copied and pasted from gdocs but the format ended up way different than most other blog/updates - I'll try to see about clearing format/etc. but maybe we should 'restrict'/limit formatting a bit for continuity (look and feel) sake.

**Comment by KatjaUlbert** [comment]
I wrote to Felix yesterday about font size continuity, concision etc. I think as long as the redesign isn´t implemented the best we can do is correcting obvious non-convormances. I´made screenshots and tagged the most frequent mistakes.
![revision_general_page_1](https://cloud.githubusercontent.com/assets/12475465/7896474/215b6714-06bb-11e5-9ccb-f1a3ac28f358.jpg)
![revision_general_page_2](https://cloud.githubusercontent.com/assets/12475465/7896475/215fc764-06bb-11e5-8558-3a9f33876a79.jpg)

**Comment by xamanu** [comment]
Thanks for the input! This is very helpful.

**Comment by xamanu** [comment]
Note to myself: Todo together with #68

**Comment by KatjaUlbert** [comment]
@russdeffner  outdated, can we close it?

**Comment by russdeffner** [comment]
Yes, I think everything was covered except 'forcing' formats in blog/update posts - but that can still be done if folks remember to 'clear formats' if they copy/paste - maybe something to still consider in redesign, but I'll close this.
