### ISSUE TITLE
Missing image at http://hotosm.org/updates/2013-03-20_learnosm_origin_and_relaunch

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/hotosm-website#75]
Hi

http://hotosm.org/updates/2013-03-20_learnosm_origin_and_relaunch

Head of the page at 
![image](https://cloud.githubusercontent.com/assets/6763965/7992282/3fbcfe90-0af6-11e5-9f36-da8a13eb1e61.png)

**Comment by russdeffner** [comment]
Hi Nick,
I don't see any image in the post - some don't have any; if there isn't one in the post there won't be the associated images like you see (many) here: http://hotosm.org/updates

**Comment by Nick-Tallguy** [comment]
Can you edit the post so the bit that reads

[inline:screen_shot_learn.png]

is not visible - because it looks like a broken link - it may just be a link to the image of the homepage for LearnOSM?

Nick

**Comment by russdeffner** [comment]
Fixed

**Comment by Nick-Tallguy** [comment]
Looks much better, thanks
