### ISSUE TITLE
website analysis (summary)

### ISSUE THREAD

**Issue by KatjaUlbert** [hotosm/hotosm-website#76]
I made a very simple visual sitemap to get a better understanding of the structure. I also considered page content like text, links, pictures. 

In general I have to say that the problem is not so much content and structure, but usability and visual conception. The mission and projects of HOT are widely covered, all the information is there. But it has to be presented in a different way to show the diversity of HOT, the variety of projects, the worldwide community and all the different ways to get involved. 

I don´t want to get too much in detail here, so this is only a summary of my main points.

Design (general): grid-based layout, 1-2 main columns plus marginal column, tiles. Application of photos, maps and infographics. Consistent use of fonts, rules for text structuring, add a second color to support the logo red→create a manual.

Homepage: every aspect of HOT should be presented here. One (or two) ongoing and prominent projects featured on top of the page. Selection of news / updates with a short introduction text and pictures. Illustrated link to “get involved” and “donate” (icon, pictrogram). I would be great to have  some “faces of HOT” here, like a volunteer profile picture with a quote.

About: a bit confusing because “about” has the same text as “the organization” page. Should “Kits” really be part of the organization? Is board=leadership?

Hot Capacities: much of the information about HOT is “hidden” here (use of OSM, partnerships, network, crisis response, data collection, community building) In my opinion every aspect diserves its own page. 

Updates: Great opportunity to show HOTs mission. Needs much more visuals. Use of columns to avoid scrolling down. 

Projects: I think every chapter (disaster, community, technical) should have a text, not only a list of ongoing and archives projects.

Get involved / Donate: both have to be much more catchy. I missed mapathons a a way to get involved.

So how do I go on from now? Start with a draft? 
![sitemap_analysis](https://cloud.githubusercontent.com/assets/12475465/8024716/b38c5f20-0d3d-11e5-94e2-ca8fc024f8b4.jpg)

**Comment by xamanu** [comment]
@KatjaUlbert This is a great overview and I think you really detected the weak points of the site. Yes, we have worked to improve content and structure so I agree on all what you said. To answer some of your questions:

> “about” has the same text as “the organization” page. Should “Kits” really be part of the organization?
This is still part of the old structure and has not been touched. Feel free to reorder this as you consider it best. We can also write new texts, or ask the communications working group to help us with them.

> Is board=leadership?
Yes, before the board was presented as leadership. But HOT is very broad and wants to be more inclusive. So there are also other "leaders" than just the board.

Yes! Please feel free to make a draft, which can be a good base to start a conversation. 
There has been a first proposal by another person, I don't want to say that it has to look like that, but it might be something to build upon: https://i.imgur.com/mxSlBaL.jpg Anyway you are the specialist!
And, by the way, there is also a special issue for the redesign: #23

**Comment by mellig** [comment]
@KatjaUlbert @xamanu I updated the wiki page containing the current content structure here: [Current content structure](https://github.com/hotosm/hotosm-website/wiki/Content-structure). A few areas have changed since Katja's outline. I have also created a page with a proposed restructuring in preparation for the redesign: [Content structure - proposal](https://github.com/hotosm/hotosm-website/wiki/Content-structure---proposed).

**Comment by KatjaUlbert** [comment]
the content structure proposal has to be updated. can we find a place to store it somewhere and close this issue?

**Comment by xamanu** [comment]
@KatjaUlbert This one? https://github.com/hotosm/hotosm-website/wiki/Content-structure---proposed
I think all feedback went in there and it has been further modfied in the process. I'd close here.

**Comment by xamanu** [comment]
Thanks Katja for this input and all the work you've done to make the redesign happen. It's now online.
