### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#78]
@KatjaUlbert made some very nice icons for hotosm.org: http://i.imgur.com/82m25H1.jpg
This is the issue to in-cooperate these and some following she promised for the working groups :)

**Comment by xamanu** [comment]
First icons are online: http://hotosm.org/get-involved

**Comment by KatjaUlbert** [comment]
I´ll send you an icon for the newsletter in a few hours.

**Comment by KatjaUlbert** [comment]
![icon_newsletter](https://cloud.githubusercontent.com/assets/12475465/8088030/c34ea234-0f9e-11e5-83c0-2c5db9113fae.jpg)

**Comment by xamanu** [comment]
Great! Thank yout! I put it online: http://hotosm.org/get-involved

How familiar are you with Git? I would like to ask you to add the source files in the repo to sites/default/themes/hot/images/source-files/icons the same way there are the others. Best way to go would be a to make a "pull request" here in Github. I'm happy to explain it to you over mumble or so, in case you haven't done it before and want some assistance.

**Comment by KatjaUlbert** [comment]
I will try to add them myself, only png or also a small preview jpg? I will store the vector files myself. Or is there a place project files are stored and shared, like cloud or server? btw I think i could do with a drupal lesson.

**Comment by KatjaUlbert** [comment]
added the newsletter icon, hopefully in the right place! I would like to exchange the working groups icon for a version with another stroke size, this one looks too thin in comparison to the othr icons. Not sure how to do this in the repo so 
![working-groups](https://cloud.githubusercontent.com/assets/12475465/8113893/65e5e944-1071-11e5-9b7a-c611b68a33f3.png)
I am attaching it here.

**Comment by xamanu** [comment]
The newsletter jpg I already included to show it on the website. I'd appreciate to have the vector and png file in the repo, as there are the other ones: https://github.com/hotosm/hotosm-website/tree/master/sites/default/themes/hot/images/source-files/icons

There general place where project files are stored and shared is the wiki: http://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team
But I think it would be good to have it in the website repo, to not loose it.

Please feel free to change the 150x150px image in the repo

**Comment by xamanu** [comment]
ok. Just to get back on track here. I think it would be good to have icons for the following:

* Project types (these would be extremely helpful to illustrate the about page and sections of projects)
  - Disaster mapping (which we already have, as it is the same as emergency mapping)
  - Community Development
  - Technical Projects
* Working groups
  - This was a proposal by @KatjaUlbert, which I agree, that it would be great to have. But maybe this is ok, to just incorporate into the new redesign..?

**Comment by xamanu** [comment]
New About page is out: http://hotosm.org/about
@KatjaUlbert do you think it would be good to develop icons as well, or what do you suggest to make this more attractive?

**Comment by KatjaUlbert** [comment]
I am not so sure about icons here, at least in the long run, we should think about a combination of picture and illustrations and maps of course. But for now we have to fill in the blanks, so we should use them,they´re also quite simple to make. Btw I am nearly finished with the working group icons:)

**Comment by KatjaUlbert** [comment]
New icons "Working groups", three versions for every group.
![icon_set2-1](https://cloud.githubusercontent.com/assets/12475465/8160859/3b6f3418-1373-11e5-80a7-c1454e753e46.jpg)
![icon_set2-2](https://cloud.githubusercontent.com/assets/12475465/8160860/3b712386-1373-11e5-99d2-f9e93f2b6277.jpg)

**Comment by xamanu** [comment]
Wow, Katja. Once again, I love them! I think thery are all in line of the existing ones and are just perfect. We also would have by them two of the three needed for an temporary about page. Only "partnertships" would be missing.

I'm giving my opinion on which of the icons I'd choose. I really like them all. But we have to select, right? :)

Activation: I lie the first one most. The second I'd throw out because it's not round enough. Then I just like the first one a bit more over the third one.

Communications: This is difficult. All are good. Very randomly I'd choose the second one. No idea why.

Fundraising: I like the first one more. It is more dynamic with the coin on the side, it looks better and expresses fundraising to me better.

Community: First one! The second would be almost the same as for "working group" itself. And last one looks more like a board (something with hierarchy).

Governance: This group should actually be renamed in my opinion. But, this is not the place to discuss this. I'd choose the second one, I like the idea of direction. The flag expresses possession to me, so I don't like it too much. And the first looks like routing.

Security: I like the second one, same reason as the coin in fundraising. I think it looks more dinamic than having just one single element.

Technical: I like second and third, because they are nice from the geek side, but I guess the first one is the one which gives a better idea to the people in general. So my vote for the first one.

Training: This is a difficult one: The first one (the book) expresses to me what the training wg is actually doing, because it has a lot to do with documentation, but it is somehow also misleading. The second one I like aesthetically most, but such a board is not usually what is used by people of the training wg. The third one is nice, y probably the most adequate, as it looks like documentation on a website.

**Comment by bgirardot** [comment]
I think they look great too and the 3 options really helps.



On 6/15/2015 5:43 PM, Felix wrote:
> Governance: This group should actually be renamed in my opinion. But,
> this is not the place to discuss this. I'd choose the second one, I like
> the idea of direction. The flag expresses possession to me, so I don't
> like it too much. And the first looks like routing.
>

Governance is not going anywhere.

How about a Gavel or a scroll, it is more about by-laws and meetings 
than anything else.

Cheers,
Blake

**Comment by KatjaUlbert** [comment]
Thanks both of you for the input @bgirardot I interpreted governance as navigation or guidance, but if it´s more about administration and management I can find another symbol. @xamanu Good choices, nearly all of them were also my favs. The third icon for "training" was supposed to be a blackboard, but if it looks like a website to you that´s great. In this case I will have to modify it and omit the sponge and the hanger.

**Comment by bgirardot** [comment]
I would say it is mostly about technical aspects of admin and management, by-laws, policy (code of conduct, etc), election procedures, etc

**Comment by KatjaUlbert** [comment]
![icons_gov train](https://cloud.githubusercontent.com/assets/12475465/8170143/f4eee63c-13ae-11e5-9704-9eb44f879eab.jpg)

**Comment by bgirardot** [comment]
The governance options are perfect.

**Comment by KatjaUlbert** [comment]
Any decision on the governance icon?

**Comment by xamanu** [comment]
I like the second most. :)
I created an image field on the working group pages, so we can upload the icons to each working group.

**Comment by KatjaUlbert** [comment]
This is the last icon in the "About" section for partnerships.
![icons_partnership](https://cloud.githubusercontent.com/assets/12475465/8397123/cdf389a4-1dc0-11e5-9852-548422205e76.jpg)

**Comment by xamanu** [comment]
Very cool! Thank you so much, Katja! I included the first one, classical handshake, as talked with @russdeffner . But what do you think? We can always change it. And in case you agree, please add the vector source files to the repo. Great work.

We have to work on getting the working groups images online, don't we?

**Comment by KatjaUlbert** [comment]
close issue?

**Comment by xamanu** [comment]
ok. this is something we are addressing in the redesign right now. Closing here.
