### ISSUE TITLE
Unable to get ways data - full.json 404

### ISSUE THREAD

**Issue by aubergene** [hotosm/hotosm-website#794]
**Actual Behaviour**

When I create a way, I try and select a feature type, if I type "road" then I see "34 results for road" at the top however nothing appears below the search for me to select.

In the browser console I see this error

`18.0cf2713b.chunk.js:1 GET https://www.openstreetmap.org/api/0.6/way/-1/full.json 404`

**Expected Behaviour**

I should get a list of feature types based on my search

**Steps to reproduce it**

I've tried it using different browsers and on different machines, have cleared cache etc. I also revoked hotsm from the OSM oauth and logged in again. Still the same issue

**Screenshots of the issue**

<img width="1791" alt="Screenshot 2021-05-27 at 12 26 51" src="https://user-images.githubusercontent.com/1710/119818238-dc237980-bee6-11eb-90bf-e8cb1fce4bc9.png">

**Comment by willemarcel** [comment]
Hi @aubergene! Thanks for your feedback. Some projects restrict the presets you can use on the editor. On the case of that project, you can only trace buildings. There is a bug in the editor that shows the wrong number of results.

**Comment by aubergene** [comment]
Thank you for explaining!
