### ISSUE TITLE
HOT organization/capacities page overhaul

### ISSUE THREAD

**Issue by xamanu** [hotosm/hotosm-website#80]
There is quite a good, but probably way to long text: http://hotosm.org/about/hot_capacities
I'd like to discuss and see if we want to improve this. What do you think we should do to give more insight information into HOT?

**Comment by KatjaUlbert** [comment]
I am not the expert here, but as I wrote in my summary I think this content is important, especially for potential collaborations and partnerships. Maybe we can handle this page like the about page? Short general introduction, one paragraph for each item that comes with a picture or illustration and the link to the respective page.

**Comment by KatjaUlbert** [comment]
Did we solve this issue?

**Comment by xamanu** [comment]
Yes, closing here.
