### ISSUE TITLE
Home Page StartBapping button leads to page not found error.

### ISSUE THREAD

**Issue by alanjacobmathew** [hotosm/hotosm-website#819]
**Actual Behaviour**
The current link to StartMapping button on HOTOSM home page leads to https://tasks.hotosm.org/learn

**Expected Behaviour**
 Either should go to https://tasks.hotosm.org/explore or https://tasks.hotosm.org/learn/map. 
If the page link to the `explore` section users can start mapping directly, and if the link is to `learn` page, new users can learn how to do 

**Steps to reproduce it**

- visit https://hotosm.org
- click on the Start Mapping button 

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes.

**Comment by dakotabenjamin** [comment]
Thanks for the contribution! I accepted the change.
