### ISSUE TITLE
Before/after map sliders

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#83]
Suggestion to include before/after map sliders somewhere. From Mikel:

"Agreed! We've been working towards that at MapGive ... at least making it easier. Tom has put together instructions on his GitHub account https://github.com/d3netxer/osm-creating-historical-tiles. It definitely requires some technical know-how at this point, but has potential to be automated. Perhaps CWG could ask the Technical Working Group to look into this. I'm sure Tom would love to collaborate with some folks in HOT on making this even better."

**Comment by techlady** [comment]
I'll put this on the agenda for the next CWG meeting (July 24). I know the Technical Working Group probably has a full slate, but this could be an excellent way to showcase what we do.

**Comment by xamanu** [comment]
Nice thing! But it needs some more complex setup, database, renderer, etc. I don't see the capacities for this to happen right now (at least in the web team). But happy to include this into the website, if there is a volunteer to set this up. If there is, then this would be great to take into consideration for the redesign process.

**Comment by mellig** [comment]
@xamanu Do you still think that this is something we should tackle with the redesign or put on a project list for later? I can suggest locations for this in the proposed content structure for the redesign.

**Comment by KatjaUlbert** [comment]
not yet implemented.

**Comment by TylerRadford** [comment]
I am going to close this since it's partially implemented with our new OSM Analytics tool.
