### ISSUE TITLE
Add partners/logos

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#86]
For partnerships and funders

**Comment by KatjaUlbert** [comment]
I think we have to reach out to the partner organisations directly to get the permission to use their logos. Usually they give out a package of files in all sizes plus guidelines.

**Comment by xamanu** [comment]
Yes, it would be good to have this confirmation from the partners. And I would declare this more or less a duplicate of #65. As I would suggest not only to put some logos on the website, but rather explain how these partnerships look like.

**Comment by KatjaUlbert** [comment]
Can we close this?

**Comment by TylerRadford** [comment]
Yes let's close and mention it will be implemented in the new design

*Tyler Radford*
Executive Director
email: tyler.radford@hotosm.org
U.S. mobile: +1 617.285.2009

*Humanitarian OpenStreetMap Team*
*Using OpenStreetMap for Humanitarian Response & Economic Development*
web <http://hotosm.org/> | twitter <https://twitter.com/hotosm> | facebook
<https://www.facebook.com/hotosm> | donate <http://hotosm.org/donate>
