### ISSUE TITLE
Add About HOT PDF for download 

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/hotosm-website#87]
Having an About document on the HOT website that people can download would be great. There is a PDF [1] that Katja and I put together that could potentially be used, as well as the Google Doc [2] version in case someone would like to edit it. Please note the PDF itself will have to be edited to remove the colour bars present for print.

[1] https://drive.google.com/open?id=0Bx3_hrMYdNwLeUlvWk43Z3ljanVwOEkyYV9SS0VFS2pxbVVF
[2] https://docs.google.com/a/hotosm.org/document/d/1iMf2JfX15flhr6a41t4M1cSNY-uYBOVCymx92Amkuyc/edit?usp=sharing

**Comment by himanshichhabra** [comment]
Hi I'm an Outreachy participant , I am interested in the redesigning and enhancing HOT website. 
I'd like to work on this issue, Can someone please guide me through this?

Thanks.

**Comment by xamanu** [comment]
@mataharimhairi This is a great idea. Unfortunately the "Organization" part of the "About" section is the one which has not been overhauled: http://hotosm.org/about/hot_capacities
IMHO it would be the most appropiate place. But right now, this is a long text that is years old. I think this should go together with improving the whole section. What do you think?

@himanshichhabra Great to hear from you! @katjaulbert and myself we are currently starting with some wireframing so we can make a redesign proposal. You are welcome to jump on and work with us!

**Comment by himanshichhabra** [comment]
@xamanu Hi , that's great, so how should i get started ? Any part of the task that I could work on?
Thanks.

**Comment by KatjaUlbert** [comment]
I think that the content of the flyer @mataharimhairi mentioned is an excellent basis for the content. I will make a screen version without marks and add this to the drive folder where all the other HOT material will be.

**Comment by russdeffner** [comment]
@himanshichhabra If no one has replied to you directly; visit http://hotosm.org/projects/outreachy for information on how to apply for the Outreachy program and more details.

**Comment by xamanu** [comment]
@KatjaUlbert Please let us know, when there is suitable text to publish as an organizational description. Thank you!

**Comment by xamanu** [comment]
Btw, this issue is heavily connected on this one: #80

**Comment by KatjaUlbert** [comment]
do we still need this?

**Comment by xamanu** [comment]
Do we want to have a flyer of HOT donwloadable on the website?

**Comment by xamanu** [comment]
I think this one here is dead. Closing for now. Please reopen in case there is interest.
