### ISSUE TITLE
Get some more obvious links to Learning how to get started mapping

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hotosm-website#88]
There needs to be links to LearnOSM and MapGive prominent.

**Comment by xamanu** [comment]
Thanks, @bgirardot! I would say this is a great input for the redesign. Tagging as such.

**Comment by KatjaUlbert** [comment]
This is now implemented on the website, can we close this issue?

**Comment by xamanu** [comment]
This is in the wireframes. So, yes, closing.
