### ISSUE TITLE
Amazon Smile Button

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#89]
Need to add Amazon Smile Button/Link and some text on the Donate page.

**Comment by xamanu** [comment]
No problem, this can be done quickly. There is an embed code you can get from: https://smile.amazon.com/ after logging in. Can you/somebody provide this?

**Comment by himanshichhabra** [comment]
@xamanu Hi, I can do this . I have logged in at Amazon smile , and now supporting Humanitarian Openstreetmap Team United States Inc .I hope that has to be selected,right? So where shall I get the code, if you can guide me to that please.
Thanks.

**Comment by russdeffner** [comment]
@himanshichhabra - no, someone (in operations/ED or Board) who has the HOT log-in needs to generate the code. Thanks though, Tyler is aware and/or on it.
=Russ

**Comment by russdeffner** [comment]
Here is a little mock-up of what I think this near-term update to the page should look like:
![donate](https://cloud.githubusercontent.com/assets/6763645/10561719/c1e3a006-74f3-11e5-9e16-170684b398ee.jpg)

**Comment by russdeffner** [comment]
Oops, didn't mean to close...

**Comment by bgirardot** [comment]
This item is under discussion by the Board. Lets put a pin in it for now.

**Comment by himanshichhabra** [comment]
@russdeffner Oh, okay . No problem ! Since, I was looking for the code on the web , I found some of the sites using the following design for the Amazon smile button, this is just to give an option. ( You can change the charity name).

![amazonsmile](https://cloud.githubusercontent.com/assets/15012159/10562628/7456d85e-7583-11e5-9ca1-8f97d304fdea.png)

**Comment by russdeffner** [comment]
@bgirardot - This issue/feature initiated as discussion with Tyler in the last Communication WG meeting.

**Comment by TylerRadford** [comment]
Here is the link. This can be shared on FB, Twitter, via email, etc. etc. Spread the word!
https://smile.amazon.com/ch/27-3166713

Here is the HTML snippet:
<div id="amznCharityBanner"><script type="text/javascript">(function() {var iFrame = document.createElement('iframe'); iFrame.style.display = 'none'; iFrame.style.border = "none"; iFrame.width = 310; iFrame.height = 256; iFrame.setAttribute && iFrame.setAttribute('scrolling', 'no'); iFrame.setAttribute('frameborder', '0'); setTimeout(function() {var contents = (iFrame.contentWindow) ? iFrame.contentWindow : (iFrame.contentDocument.document) ? iFrame.contentDocument.document : iFrame.contentDocument; contents.document.open(); contents.document.write(decodeURIComponent("%3Cdiv%20id%3D%22amznCharityBannerInner%22%3E%3Ca%20href%3D%22https%3A%2F%2Fsmile.amazon.com%2Fch%2F27-3166713%22%20target%3D%22_blank%22%3E%3Cdiv%20class%3D%22text%22%20height%3D%22%22%3E%3Cdiv%20class%3D%22support-wrapper%22%3E%3Cdiv%20class%3D%22support%22%20style%3D%22font-size%3A%2025px%3B%20line-height%3A%2028px%3B%20margin-top%3A%201px%3B%20margin-bottom%3A%201px%3B%22%3ESupport%20%3Cspan%20id%3D%22charity-name%22%20style%3D%22display%3A%20inline-block%3B%22%3EHumanitarian%20OpenStreetMap%20Team.%3C%2Fspan%3E%3C%2Fdiv%3E%3C%2Fdiv%3E%3Cp%20class%3D%22when-shop%22%3EWhen%20you%20shop%20at%20%3Cb%3Esmile.amazon.com%2C%3C%2Fb%3E%3C%2Fp%3E%3Cp%20class%3D%22donates%22%3EAmazon%20donates.%3C%2Fp%3E%3C%2Fdiv%3E%3C%2Fa%3E%3C%2Fdiv%3E%3Cstyle%3E%23amznCharityBannerInner%7Bbackground-image%3Aurl(https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2Fx-locale%2Fpaladin%2Fcharitycentral%2Fbanner-background-image._CB309675353_.png)%3Bwidth%3A300px%3Bheight%3A250px%3Bposition%3Arelative%7D%23amznCharityBannerInner%20a%7Bdisplay%3Ablock%3Bwidth%3A100%25%3Bheight%3A100%25%3Bposition%3Arelative%3Bcolor%3A%23000%3Btext-decoration%3Anone%7D.text%7Bposition%3Aabsolute%3Btop%3A20px%3Bleft%3A15px%3Bright%3A15px%3Bbottom%3A100px%7D.support-wrapper%7Boverflow%3Ahidden%3Bmax-height%3A86px%7D.support%7Bfont-family%3AArial%2Csans%3Bfont-weight%3A700%3Bline-height%3A28px%3Bfont-size%3A25px%3Bcolor%3A%23333%3Btext-align%3Acenter%3Bmargin%3A0%3Bpadding%3A0%3Bbackground%3A0%200%7D.when-shop%7Bfont-family%3AArial%2Csans%3Bfont-size%3A15px%3Bfont-weight%3A400%3Bline-height%3A25px%3Bcolor%3A%23333%3Btext-align%3Acenter%3Bmargin%3A0%3Bpadding%3A0%3Bbackground%3A0%200%7D.donates%7Bfont-family%3AArial%2Csans%3Bfont-size%3A15px%3Bfont-weight%3A400%3Bline-height%3A21px%3Bcolor%3A%23333%3Btext-align%3Acenter%3Bmargin%3A0%3Bpadding%3A0%3Bbackground%3A0%200%7D%3C%2Fstyle%3E")); contents.document.close(); iFrame.style.display = 'block';}); document.getElementById('amznCharityBanner').appendChild(iFrame); })(); </script></div>

**Comment by xamanu** [comment]
Done: http://hotosm.org/donate
Please test and close this issue if all fine. Thanks!

**Comment by russdeffner** [comment]
Agree closely related to #79 so specifically to this issue, I tested and the button works. Closing this and we can discuss aesthetics and such on the other issue.
