### ISSUE TITLE
make the user profile Country field a list to choose from

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/hotosm-website#9]

**Comment by xamanu** [comment]
* I saw, we can still add new countries (names) to the select list or manage the country list, in case it is not adequate in a certain case. I don't expect this to happen all the time, so manual adjustment should be fine.
* To ask everybody to login is going to be necessary, as we want to have a nice view with user images of all members (#15). I would suggest to define a bit more, what all should come from the users and then, indeed ask them to login and complete the information.
* It is just a big value to have structured data, so we can select, search or build views on people's country. A good time to get the data together now, so we can use them for nice things in the future.

**Comment by xamanu** [comment]
This caused problems that needed to be fixed rapidly, because no user profile was able to be saved, so I proceeded in the implementation.
