### ISSUE TITLE
Extra field displaying on Newsletter sign up confirmation message

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#91]
![screenshot_2015-10-28-22-43-15](https://cloud.githubusercontent.com/assets/9853903/10801783/280b7ce4-7dca-11e5-97c5-940596435ec1.png)
I am a..." field appears after signing up, at least on mobile
![screenshot_2015-10-28-22-43-15](https://cloud.githubusercontent.com/assets/9853903/10801766/12bc198e-7dca-11e5-9595-9587b5883b8a.png)

**Comment by xamanu** [comment]
Ha, I though this was website related. This is actually the content of the confirmation email which is sent directly by Mailchimp. I guess in Mailchimp's admin interface this is configurable. Grace (no idea if she is on Github) was configuring this, I think. I have no access to this.

As it comes to the website I can just offer to disable the confirmation emails, if wanted.

**Comment by xamanu** [comment]
Grace took this field off and informed me over email. Thanks for reporting, @TylerRadford. Closing here.
