### ISSUE TITLE
Constant URL for important HOT documents

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#92]
We need a way to keep the URL current for important HOT documents like Bylaws, Policies, etc. As example, we will want to update (not very frequently) something like the Activation Protocol, but it is linked and referenced in many places at the URL: https://hotosm.org/sites/default/files/HOTActivationProtocol.pdf - for me to update it from it's 'static page': https://hotosm.org/projects/hot_training_center - I have to remove and re-upload which changed the URL to: https://hotosm.org/sites/default/files/HOTActivationProtocol_0.pdf @xamanu - can you change the URL back to 'without _0'? And as we anticipate updates to Bylaws and Membership Code in the near future, we need a way to update those without changing the URL as well since they are linked from places like the wiki, HOT Training Center, etc.

**Comment by xamanu** [comment]
I think we solved this by using a node for documents. For example: https://hotosm.org/by_laws

**Comment by KatjaUlbert** [comment]
@russdeffner can we close this issue?
