### ISSUE TITLE
social plug-ins

### ISSUE THREAD

**Issue by KatjaUlbert** [hotosm/hotosm-website#93]
I think it would be useful to have social plug-in for posts and updates, like facebook like, share tweet or google +1. and maybe also embedded posts and tweets.

**Comment by mellig** [comment]
@KatjaUlbert I can see embedding posts and/or tweets on the home page as a good location. Is there anywhere else you think it would be good to display a social media feed?

**Comment by KatjaUlbert** [comment]
I think the homepage is the best place for tweets/post. Do you have any other suggestions?

**Comment by xamanu** [comment]
Just an idea to throw in: It could be also in the footer

**Comment by mellig** [comment]
After looking over the conversation I realize that there are (at least) three different ways social media can be used on the site:
1) Links to the HOT accounts (HOT twitter, HOT facebook) - might be best as a constant presence, in the footer perhaps as @xamanu suggested?
2) An embedded, live stream of social media updates, such as all tweets having to do with HOT - homepage
3) A way to send a tweet related to HOT, for example a twitter button that allows you to share a tweet about a HOT project on that project page
