### ISSUE TITLE
Add Guidestar logo to website

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#95]
Congratulations on achieving a Gold level profile with GuideStar. This is a testament to your organization’s commitment to data transparency.

By keeping your profile up-to-date with GuideStar, you are ensuring that timely and accurate information about your nonprofit reaches the 7+ million annual visitors to GuideStar, and millions of other viewers reached through GuideStar’s network of donation providers, search engines, donor-advised funds, foundations, and more.

We hope you will take advantage of the benefits you have earned, such as a Gold widget and logo to proudly display on your website or in your print materials. You can access these benefits by logging in to update your profile and clicking on the "Benefits & Rewards" tab.

**Comment by xamanu** [comment]
I think if we really want to put such kind of logos to the website, we need to make space in the design for it.

**Comment by TylerRadford** [comment]
Yep agree. We should plan for space for others too (such as Charity Navigator). See www.savethechildren.org for an example (scroll down)

**Comment by mellig** [comment]
I think this type of endorsement/approval logo would be best suited to a space in the footer, either linking directly to the endorsement's site, or to a page on HOT that would explain the significance of the endorsement.

**Comment by bgirardot** [comment]
@mellig +1 to these logos being on the footer of every page

**Comment by KatjaUlbert** [comment]
this will be implemented, can we close this issue?

**Comment by TylerRadford** [comment]
I think we can close and mention that it will be implemented in the new
design

*Tyler Radford*
Executive Director
email: tyler.radford@hotosm.org
U.S. mobile: +1 617.285.2009

*Humanitarian OpenStreetMap Team*
*Using OpenStreetMap for Humanitarian Response & Economic Development*
web <http://hotosm.org/> | twitter <https://twitter.com/hotosm> | facebook
<https://www.facebook.com/hotosm> | donate <http://hotosm.org/donate>

**Comment by KatjaUlbert** [comment]
@TylerRadford you opened it so you are the only one who can close it:D

**Comment by xamanu** [comment]
@TylerRadford What specific Guidestart logo (with transparent background preferably) should we integrate? Can you provide one. Thanks!

**Comment by TylerRadford** [comment]
`<a href="http://www.guidestar.org/organizations/27-3166713/humanitarian-openstreetmap-team.aspx" target="_blank">
    <img src="http://widgets.guidestar.org/gximage2?o=9229194&l=v4" />
</a>
                            `

**Comment by TylerRadford** [comment]
![image](https://cloud.githubusercontent.com/assets/9853903/13082328/42e0b34c-d49e-11e5-9144-9bfde80b5b3a.png)

**Comment by xamanu** [comment]
It's online. Thanks!
