### ISSUE TITLE
A map to showcase our maps

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#96]
Related to issue #94 we are great at mapping but could use improvement in showing off our global work! Suggest a map of HOT projects. If we want, we can differentiate between a HOT donor funded field mapping project, a HOT member project, and a HOT remote mapping (Missing Maps) project. Perhaps someone can figure out where and how this was created and we can update it.

![image](https://cloud.githubusercontent.com/assets/9853903/11958478/1449851a-a896-11e5-9c61-d3aa80308fed.png)

**Comment by KatjaUlbert** [comment]
this would be the HOT footprints from Pratik http://pratikyadav.github.io/HOT-Task-Map/#3/22.76/-25.84

**Comment by TylerRadford** [comment]
Yes - this could be a good one - is there somewhere we can feature it on
one of our pages?

*Tyler Radford*
Executive Director
email: tyler.radford@hotosm.org
U.S. mobile: +1 617.285.2009

*Humanitarian OpenStreetMap Team*
*Using OpenStreetMap for Humanitarian Response & Economic Development*
web <http://hotosm.org/> | twitter <https://twitter.com/hotosm> | facebook
<https://www.facebook.com/hotosm> | donate <http://hotosm.org/donate>

**Comment by xamanu** [comment]
Closing as duplicate. Please continue discussion here: #84.
