### ISSUE TITLE
Static Pages for Documents

### ISSUE THREAD

**Issue by russdeffner** [hotosm/hotosm-website#97]
Hello, just as a place to document, we created static pages for our 'core documents' but a few are not linked from anywhere, here are the ones I know about (or created myself):

- Articles of Incorporation: https://hotosm.org/our_board/incorporation (this one probably needs cleaned up and original AoI PDF'd?)
- Bylaws: https://hotosm.org/by_laws
- Membership Code/Code of Conduct: https://hotosm.org/hot_membership_code
- Activation Protocol: https://hotosm.org/activation_protocol

**Comment by xamanu** [comment]
@russdeffner Which ones are not linked from anywhere? Instead of creating this static page for documents, I'd rather make sure that the documents are linked where they make sense.

**Comment by russdeffner** [comment]
To refresh the idea - we have several of these documents that are expected to be updated 'regularly', so the static page was used versus needing to maintain/version for a document URL. Has that changed/can we do that more easily now?

**Comment by xamanu** [comment]
Yes, I remember this. Do you want an internal view to have an oversight of these type of nodes we use to upload files?

**Comment by russdeffner** [comment]
Is there a manual :) 
On another note, it needs to be manageable as we transition, so the next Chair will (in theory) be doing the next updates for Code/Bylaws/etc. - or Board, i.e. it needs to be fairly clear or have a bit of instruction somewhere. Or I guess if they don't know, they can open issue for help?

**Comment by xamanu** [comment]
Yes, it would be good to write down in a manual how we manage files now, etc... Please start writing this down, you are the perfect person to do it, as you know the information you'd need

**Comment by russdeffner** [comment]
ok, on my to-do.

**Comment by xamanu** [comment]
Closing, because this should be treated in the manual.
