### ISSUE TITLE
Partners Page

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/hotosm-website#98]
Looking at the Partners page (or potential page) on hotosm.org. Peace Corps would be great to add — they do so much. Also Youth Mappers, good to mention USAID.

@TylerRadford

**Comment by xamanu** [comment]
The partnerships page is about to be launched. @TylerRadford, please review it and if possible, please add the partners mentioned here before. Thanks!

**Comment by TylerRadford** [comment]
Hi all, looks pretty good. I suggest making the logos about half of the current size so you can see more on a single page without scrolling.

Second, are we still planning to create a link between the "Partner" content type and the "Project" type? I recall there was a link proposed in the design mockups.

It would be nice to have each partner's logo clickable to go to a partner "single page" and see detail on the projects that we have collaborated on.

Also we need to add a URL for each partner that would be clickable from the Partner single page.

**Comment by mikelmaron** [comment]
Suggestions
* Mention USAID under YouthMappers
* Add Peace Corps
* Do commercial / imagery partners belong here or elsewhere?

**Comment by xamanu** [comment]
Yes for the links to projects the partner is assigned to. And we can also create special partner pages. I will be working on this.

**Comment by TylerRadford** [comment]
I added Peace Corps and adjusted text for YouthMappers. Yes imagery partners could also go here. I'd like to wait a short bit for these (starting with DG).

**Comment by TylerRadford** [comment]
Also need to sort Partners by alphabetical order and ensure all their logos appear to be the same size.

**Comment by xamanu** [comment]
@TylerRadford The Partnerships section is comming together. Now, when editing projects pages you can add partners to them. Please do, so I can tackle design issues when having them added. Thanks!

**Comment by xamanu** [comment]
@TylerRadford Theming should be fine now. Please check and confirm, then I put the link in the main menu. Cheers.

**Comment by xamanu** [comment]
The path is already live, but not in the menu, until confirmed: https://hotosm.org/partnerships

**Comment by TylerRadford** [comment]
Hi @xamanu when editing partners I can only see Title Body and Image fields, no field to link to projects or field for the partner's URL. Could you check?

**Comment by TylerRadford** [comment]
Also, could we see what it looks like with logos left-aligned. Since they currently centered, each row looks like it currently has a different amount of space between each of the two partner logos. Left aligned might make it appear more consistent.

**Comment by xamanu** [comment]
- Please select partners on projects, not projects on partners.
- Logos in the design are always centered. Changing this would be clearly inconsistent.
- I agree, it would be good to have a partner website field on partners (feature request)

**Comment by xamanu** [comment]
Added url field for partner's website url.

**Comment by TylerRadford** [comment]
Thanks Felix

Logos should be left-aligned per the design. Pls see https://moqups.com/#!/edit/mellig/NLnozD7i and https://drive.google.com/folderview?id=0B9J_lNJIscUzbmNlQ3YtWVRUeTg&usp=gmail

**Comment by xamanu** [comment]
ok. I still think it's inconsistent. But approved is approved :smile:
Now it's left. Good to go?

**Comment by TylerRadford** [comment]
The whole thing looks great, thanks. Yes please publish (and with a link in the top nav). I am adding URLs and links to projects.

**Comment by xamanu** [comment]
Done. Closing this issue.
