### ISSUE TITLE
Whitespace inconsistent above and below top blog update

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/hotosm-website#99]
If no photo for first blog post...too much whitespace above and below the post

![image](https://cloud.githubusercontent.com/assets/9853903/14753715/116b79f6-08a5-11e6-8a60-6c619ad8e970.png)

**Comment by xamanu** [comment]
The new design requires a news item to have an image. So I set the images field on updates to "required". Thanks for reporting!

**Comment by TylerRadford** [comment]
Image appears twice if added in text in order to display on update node page.

![image](https://cloud.githubusercontent.com/assets/9853903/14968733/80c70e20-108c-11e6-8734-40bb0e8a65ca.png)
![Uploading image.png…]()

**Comment by xamanu** [comment]
Please make use of the "summary" functionality on each node edit form. So that the image is not in the teaser text. Thanks!
